"""
Validation Suite
=================
Output container for the dynamic suite generator.

A ValidationSuite holds every generated query, the profile that triggered
it, and enough metadata to write SQL files, YAML configs, and reports.

Design principle: one suite = one source table → one target table.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from profiling.schema_profiler import TableProfile
from profiling.validation_rule_engine import ValidationRequirement, ValidationType
from profiling.ai_recommendation import AIRecommendation


# ---------------------------------------------------------------------------
# Single generated query pair
# ---------------------------------------------------------------------------

@dataclass
class GeneratedQuery:
    """
    One generated SQL query (source side) and its target counterpart.

    Attributes
    ----------
    requirement     : The ValidationRequirement that triggered this query
    label           : Short label (used as SQL block header)
    source_sql      : SQL to run on PostgreSQL
    target_sql      : SQL to run on Snowflake
    comparison_note : How to compare the results of source vs target
    query_number    : Display number pair (e.g. "⑨ / ⑩")
    is_baseline     : True for the 8 mandatory checks
    """
    requirement:     ValidationRequirement
    label:           str
    source_sql:      str
    target_sql:      str
    comparison_note: str = ""
    query_number:    str = ""
    is_baseline:     bool = False


# ---------------------------------------------------------------------------
# Full validation suite
# ---------------------------------------------------------------------------

@dataclass
class ValidationSuite:
    """
    Complete dynamic validation suite for one table pair.

    Attributes
    ----------
    source_schema       : PostgreSQL schema
    source_table        : PostgreSQL table
    target_database     : Snowflake database
    target_schema       : Snowflake schema
    target_table        : Snowflake table
    profile             : TableProfile used to build the suite
    requirements        : Ordered list of ValidationRequirement
    queries             : All generated SQL pairs
    ai_recommendations  : AI-suggested checks (may be empty)
    generated_at        : ISO timestamp
    generated_by        : 'ai' | 'static' | 'mixed'
    model_used          : AI model name if AI was active
    has_fivetran_active : Whether Snowflake target has _FIVETRAN_ACTIVE
    """

    source_schema:    str = ""
    source_table:     str = ""
    target_database:  str = ""
    target_schema:    str = ""
    target_table:     str = ""

    profile:          Optional[TableProfile] = None
    requirements:     List[ValidationRequirement] = field(default_factory=list)
    queries:          List[GeneratedQuery] = field(default_factory=list)
    ai_recommendations: List[AIRecommendation] = field(default_factory=list)

    generated_at:     str = field(default_factory=lambda: datetime.now().isoformat())
    generated_by:     str = "static"
    model_used:       str = "N/A"
    has_fivetran_active: bool = False

    # ── Derived properties ─────────────────────────────────────────────────

    @property
    def baseline_queries(self) -> List[GeneratedQuery]:
        return [q for q in self.queries if q.is_baseline]

    @property
    def conditional_queries(self) -> List[GeneratedQuery]:
        return [q for q in self.queries if not q.is_baseline]

    @property
    def total_query_pairs(self) -> int:
        return len(self.queries)

    @property
    def source_full(self) -> str:
        return f"{self.source_schema}.{self.source_table}"

    @property
    def target_full(self) -> str:
        parts = [p for p in [self.target_database, self.target_schema, self.target_table] if p]
        return ".".join(parts)

    # ── Combined SQL output ────────────────────────────────────────────────

    def to_combined_sql(self) -> str:
        """
        Produce one .sql file with all source + target queries, clearly labelled.
        """
        sep  = "=" * 72
        dash = "─" * 72

        header_lines = [
            f"-- {sep}",
            f"-- DYNAMIC MIGRATION VALIDATOR — Generated Validation Suite",
            f"-- Source       : {self.source_full}",
            f"-- Target       : {self.target_full}",
            f"-- Generated    : {self.generated_at}",
            f"-- Generated by : {self.generated_by.upper()}",
            f"-- AI Model     : {self.model_used}",
            f"-- Total checks : {self.total_query_pairs} query pair(s)",
            f"-- Fivetran     : {'YES — WHERE _FIVETRAN_ACTIVE = TRUE' if self.has_fivetran_active else 'NO'}",
            f"-- {sep}",
            "",
            "-- HOW TO USE:",
            "-- 1. Run each SOURCE query on PostgreSQL, each TARGET on Snowflake.",
            "-- 2. Compare the result sets as instructed in the comparison note.",
            "-- 3. Any row-count difference OR value mismatch = FAIL.",
            "-- 4. Aggregate queries (MIN/MAX/SUM) are combined — compare columns.",
            f"-- {sep}",
            "",
        ]

        blocks: List[str] = []
        for gq in self.queries:
            src_block = (
                f"-- {dash}\n"
                f"-- SOURCE {gq.query_number} — {gq.label}\n"
                f"-- {dash}\n"
                f"{gq.source_sql}\n"
            )
            tgt_block = (
                f"-- {dash}\n"
                f"-- TARGET {gq.query_number} — {gq.label}\n"
                f"-- {dash}\n"
                f"{gq.target_sql}\n"
            )
            if gq.comparison_note:
                src_block = src_block.rstrip("\n") + f"\n-- Compare: {gq.comparison_note}\n"

            blocks.append(src_block)
            blocks.append(tgt_block)
            blocks.append("")

        # AI recommendations (as comments only — not executable SQL)
        if self.ai_recommendations:
            rec_lines = [
                f"-- {sep}",
                f"-- AI-RECOMMENDED BUSINESS RULE CHECKS",
                f"-- These are condition fragments. Run as:",
                f"--   SELECT COUNT(*) FROM <table> WHERE NOT (<condition>);",
                f"-- Any count > 0 = data quality issue.",
                f"-- {sep}",
                "",
            ]
            for rec in self.ai_recommendations:
                rec_lines.append(rec.as_sql_comment())
                rec_lines.append(
                    f"-- Run on PostgreSQL:\n"
                    f"SELECT COUNT(*) AS violating_rows\n"
                    f"FROM {self.source_full}\n"
                    f"WHERE NOT ({rec.pg_expr});\n"
                )
                rec_lines.append(
                    f"-- Run on Snowflake:\n"
                    f"SELECT COUNT(*) AS violating_rows\n"
                    f"FROM {self.target_full}\n"
                    f"{'WHERE _FIVETRAN_ACTIVE = TRUE AND ' if self.has_fivetran_active else 'WHERE '}"
                    f"NOT ({rec.sf_expr});\n"
                )
                rec_lines.append("")
            blocks.extend(rec_lines)

        return "\n".join(header_lines + blocks)

    def to_summary_dict(self) -> Dict[str, Any]:
        """Return a summary dict for logging and JSON report embedding."""
        return {
            "source_table": self.source_full,
            "target_table": self.target_full,
            "generated_at": self.generated_at,
            "generated_by": self.generated_by,
            "model_used": self.model_used,
            "has_fivetran_active": self.has_fivetran_active,
            "total_query_pairs": self.total_query_pairs,
            "baseline_count": len(self.baseline_queries),
            "conditional_count": len(self.conditional_queries),
            "ai_recommendation_count": len(self.ai_recommendations),
            "requirements": [
                {
                    "type": r.validation_type.value,
                    "label": r.label,
                    "columns": r.column_names,
                    "is_conditional": r.is_conditional,
                    "reason": r.reason,
                }
                for r in self.requirements
            ],
        }
