-- ======================================================================
-- MIGRATION VALIDATOR — Generated Validation Queries
-- Table        : AcctSoftware
-- Source       : postgresql://dbo.AcctSoftware
-- Target       : snowflake://DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
-- Generated    : 2026-08-12T17:45:34.114190
-- Generated by : AI
-- AI Model     : gpt-4o
-- Primary Keys : NONE — No primary key detected — duplicate/missing row checks (⑨-⑭) skipped. Declare primary_keys in your batch YAML to enable them.
-- ======================================================================
-- HOW TO USE:
--   ① Run on PostgreSQL  → compare count with ②
--   ② Run on Snowflake   → compare count with ①
--   ③ Run on PostgreSQL  → export to CSV
--   ④ Run on Snowflake   → export to CSV
--   Compare ③ vs ④ row-by-row — must be IDENTICAL
--   ⑤ Run on PostgreSQL  → compare NULL % with ⑥
--   ⑥ Run on Snowflake   → compare NULL % with ⑤
--   ⑦ Run on PostgreSQL  → compare distinct counts with ⑧
--   ⑧ Run on Snowflake   → compare distinct counts with ⑦
-- ======================================================================
-- ──────────────────────────────────────────────────────────────────────
-- ① ROW COUNT — PostgreSQL (Expected: matches ②)
-- ──────────────────────────────────────────────────────────────────────
-- ① ROW COUNT: PostgreSQL (dbo.AcctSoftware)
SELECT COUNT(*) AS source_row_count
FROM dbo.AcctSoftware;

-- ──────────────────────────────────────────────────────────────────────
-- ② ROW COUNT — Snowflake  (Expected: matches ①)
-- ──────────────────────────────────────────────────────────────────────
-- ② ROW COUNT: Snowflake (DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE)
SELECT COUNT(*) AS target_row_count
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
WHERE _FIVETRAN_ACTIVE = TRUE;

-- ──────────────────────────────────────────────────────────────────────
-- ③ MAIN VALIDATION — PostgreSQL (normalised data — export CSV, compare with ④)
-- ──────────────────────────────────────────────────────────────────────
-- ③ SOURCE: PostgreSQL (dbo.AcctSoftware)
SELECT
    COALESCE(CAST(CAST(AcctSoftwareID AS TEXT) AS TEXT), '<<NULL>>') AS AcctSoftwareID_normalized,
    COALESCE(CAST(TRIM(sSoftwareName) AS TEXT), '<<NULL>>') AS sSoftwareName_normalized,
    COALESCE(CAST(CASE WHEN bPermanent = true THEN '1' WHEN bPermanent = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS bPermanent_normalized,
    COALESCE(CAST(TO_CHAR(dDeleted, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS dDeleted_normalized,
    COALESCE(CAST(TO_CHAR(dUpdated, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS dUpdated_normalized,
    COALESCE(CAST(TRIM(uTS) AS TEXT), '<<NULL>>') AS uTS_normalized,
    COALESCE(CAST(CAST(OldPK AS TEXT) AS TEXT), '<<NULL>>') AS OldPK_normalized
FROM dbo.AcctSoftware;

-- ──────────────────────────────────────────────────────────────────────
-- ④ MAIN VALIDATION — Snowflake  (normalised data — export CSV, compare with ③)
-- ──────────────────────────────────────────────────────────────────────
-- ④ TARGET: Snowflake (DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE)
SELECT
    COALESCE(CAST(CAST(ACCTSOFTWAREID AS STRING) AS STRING), '<<NULL>>') AS AcctSoftwareID_normalized,
    COALESCE(CAST(TRIM(SSOFTWARENAME) AS STRING), '<<NULL>>') AS sSoftwareName_normalized,
    COALESCE(CAST(CASE WHEN BPERMANENT = TRUE THEN '1' WHEN BPERMANENT = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS bPermanent_normalized,
    COALESCE(CAST(TO_VARCHAR(DDELETED, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS dDeleted_normalized,
    COALESCE(CAST(TO_VARCHAR(DUPDATED, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS dUpdated_normalized,
    COALESCE(CAST(TRIM(UTS) AS STRING), '<<NULL>>') AS uTS_normalized,
    COALESCE(CAST(CAST(OLDPK AS STRING) AS STRING), '<<NULL>>') AS OldPK_normalized
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
WHERE _FIVETRAN_ACTIVE = TRUE;

-- ──────────────────────────────────────────────────────────────────────
-- ⑤ NULL % PER COLUMN — PostgreSQL (compare null_pct values with ⑥)
-- ──────────────────────────────────────────────────────────────────────
-- ⑤ NULL % CHECK: PostgreSQL (dbo.AcctSoftware)
SELECT
    COUNT(*) AS total_rows,
    ROUND(100.0 * SUM(CASE WHEN AcctSoftwareID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS AcctSoftwareID_null_pct,
    ROUND(100.0 * SUM(CASE WHEN sSoftwareName IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS sSoftwareName_null_pct,
    ROUND(100.0 * SUM(CASE WHEN bPermanent IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS bPermanent_null_pct,
    ROUND(100.0 * SUM(CASE WHEN dDeleted IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS dDeleted_null_pct,
    ROUND(100.0 * SUM(CASE WHEN dUpdated IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS dUpdated_null_pct,
    ROUND(100.0 * SUM(CASE WHEN uTS IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS uTS_null_pct,
    ROUND(100.0 * SUM(CASE WHEN OldPK IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS OldPK_null_pct
FROM dbo.AcctSoftware;

-- ──────────────────────────────────────────────────────────────────────
-- ⑥ NULL % PER COLUMN — Snowflake  (compare null_pct values with ⑤)
-- ──────────────────────────────────────────────────────────────────────
-- ⑥ NULL % CHECK: Snowflake (DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE)
SELECT
    COUNT(*) AS total_rows,
    ROUND(100.0 * SUM(CASE WHEN ACCTSOFTWAREID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS AcctSoftwareID_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SSOFTWARENAME IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS sSoftwareName_null_pct,
    ROUND(100.0 * SUM(CASE WHEN BPERMANENT IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS bPermanent_null_pct,
    ROUND(100.0 * SUM(CASE WHEN DDELETED IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS dDeleted_null_pct,
    ROUND(100.0 * SUM(CASE WHEN DUPDATED IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS dUpdated_null_pct,
    ROUND(100.0 * SUM(CASE WHEN UTS IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS uTS_null_pct,
    ROUND(100.0 * SUM(CASE WHEN OLDPK IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS OldPK_null_pct
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
WHERE _FIVETRAN_ACTIVE = TRUE;

-- ──────────────────────────────────────────────────────────────────────
-- ⑦ DISTINCT VALUE COUNT — PostgreSQL (compare distinct_count with ⑧)
-- ──────────────────────────────────────────────────────────────────────
-- ⑦ DISTINCT VALUE COUNT: PostgreSQL (dbo.AcctSoftware)
-- Compare distinct counts with ⑧ — large differences indicate data drift.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT AcctSoftwareID) AS AcctSoftwareID_distinct_count,
    COUNT(DISTINCT sSoftwareName) AS sSoftwareName_distinct_count,
    COUNT(DISTINCT bPermanent) AS bPermanent_distinct_count,
    COUNT(DISTINCT dDeleted) AS dDeleted_distinct_count,
    COUNT(DISTINCT dUpdated) AS dUpdated_distinct_count,
    COUNT(DISTINCT uTS) AS uTS_distinct_count,
    COUNT(DISTINCT OldPK) AS OldPK_distinct_count
FROM dbo.AcctSoftware;

-- ──────────────────────────────────────────────────────────────────────
-- ⑧ DISTINCT VALUE COUNT — Snowflake  (compare distinct_count with ⑦)
-- ──────────────────────────────────────────────────────────────────────
-- ⑧ DISTINCT VALUE COUNT: Snowflake (DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE)
-- Compare distinct counts with ⑦ — large differences indicate data drift.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ACCTSOFTWAREID) AS AcctSoftwareID_distinct_count,
    COUNT(DISTINCT SSOFTWARENAME) AS sSoftwareName_distinct_count,
    COUNT(DISTINCT BPERMANENT) AS bPermanent_distinct_count,
    COUNT(DISTINCT DDELETED) AS dDeleted_distinct_count,
    COUNT(DISTINCT DUPDATED) AS dUpdated_distinct_count,
    COUNT(DISTINCT UTS) AS uTS_distinct_count,
    COUNT(DISTINCT OLDPK) AS OldPK_distinct_count
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
WHERE _FIVETRAN_ACTIVE = TRUE;
