-- ========================================================================
-- DYNAMIC MIGRATION VALIDATOR — Generated Validation Suite
-- Source       : dbo.AcctSoftware
-- Target       : DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
-- Generated    : 2026-08-12T17:45:39.054459
-- Generated by : AI
-- AI Model     : gpt-4o
-- Total checks : 3 query pair(s)
-- Fivetran     : YES — WHERE _FIVETRAN_ACTIVE = TRUE
-- ========================================================================

-- HOW TO USE:
-- 1. Run each SOURCE query on PostgreSQL, each TARGET on Snowflake.
-- 2. Compare the result sets as instructed in the comparison note.
-- 3. Any row-count difference OR value mismatch = FAIL.
-- 4. Aggregate queries (MIN/MAX/SUM) are combined — compare columns.
-- ========================================================================

-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ① ROW COUNT: PostgreSQL (dbo.AcctSoftware)
SELECT COUNT(*) AS source_row_count
FROM dbo.AcctSoftware;
-- Compare: source_row_count must equal target_row_count

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ② ROW COUNT: Snowflake (DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE)
SELECT COUNT(*) AS target_row_count
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ③ SOURCE: PostgreSQL (dbo.AcctSoftware)
SELECT
    COALESCE(CAST(CAST(AcctSoftwareID AS TEXT) AS TEXT), '<<NULL>>') AS AcctSoftwareID_normalized,
    COALESCE(CAST(TRIM(sSoftwareName) AS TEXT), '<<NULL>>') AS sSoftwareName_normalized,
    COALESCE(CAST(CASE WHEN bPermanent = true THEN '1' WHEN bPermanent = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS bPermanent_normalized,
    COALESCE(CAST(TO_CHAR(dDeleted, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS dDeleted_normalized,
    COALESCE(CAST(TO_CHAR(dUpdated, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS dUpdated_normalized,
    COALESCE(CAST(TRIM(uTS) AS TEXT), '<<NULL>>') AS uTS_normalized,
    COALESCE(CAST(CAST(OldPK AS TEXT) AS TEXT), '<<NULL>>') AS OldPK_normalized
FROM dbo.AcctSoftware;
-- Compare: Export both to CSV. Compare row-by-row — must be identical. All values are normalised so comparison is type-safe.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ④ TARGET: Snowflake (DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE)
SELECT
    COALESCE(CAST(CAST(ACCTSOFTWAREID AS STRING) AS STRING), '<<NULL>>') AS AcctSoftwareID_normalized,
    COALESCE(CAST(TRIM(SSOFTWARENAME) AS STRING), '<<NULL>>') AS sSoftwareName_normalized,
    COALESCE(CAST(CASE WHEN BPERMANENT = TRUE THEN '1' WHEN BPERMANENT = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS bPermanent_normalized,
    COALESCE(CAST(TO_VARCHAR(DDELETED, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS dDeleted_normalized,
    COALESCE(CAST(TO_VARCHAR(DUPDATED, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS dUpdated_normalized,
    COALESCE(CAST(TRIM(UTS) AS STRING), '<<NULL>>') AS uTS_normalized,
    COALESCE(CAST(CAST(OLDPK AS STRING) AS STRING), '<<NULL>>') AS OldPK_normalized
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + MIN/MAX + VALUE_DIST)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: PostgreSQL (dbo.AcctSoftware)
-- Includes: NULL% + DISTINCT + MIN/MAX + VALUE_DIST
-- One scan replaces 4 separate aggregate query types.
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN AcctSoftwareID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS AcctSoftwareID_null_pct
    ROUND(100.0 * SUM(CASE WHEN sSoftwareName IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS sSoftwareName_null_pct
    ROUND(100.0 * SUM(CASE WHEN bPermanent IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS bPermanent_null_pct
    ROUND(100.0 * SUM(CASE WHEN dDeleted IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS dDeleted_null_pct
    ROUND(100.0 * SUM(CASE WHEN dUpdated IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS dUpdated_null_pct
    ROUND(100.0 * SUM(CASE WHEN uTS IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS uTS_null_pct
    ROUND(100.0 * SUM(CASE WHEN OldPK IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS OldPK_null_pct
    COUNT(DISTINCT AcctSoftwareID) AS AcctSoftwareID_distinct_count
    COUNT(DISTINCT sSoftwareName) AS sSoftwareName_distinct_count
    COUNT(DISTINCT bPermanent) AS bPermanent_distinct_count
    COUNT(DISTINCT dDeleted) AS dDeleted_distinct_count
    COUNT(DISTINCT dUpdated) AS dUpdated_distinct_count
    COUNT(DISTINCT uTS) AS uTS_distinct_count
    COUNT(DISTINCT OldPK) AS OldPK_distinct_count
    MIN(AcctSoftwareID) AS AcctSoftwareID_min
    MAX(AcctSoftwareID) AS AcctSoftwareID_max
    MIN(OldPK) AS OldPK_min
    MAX(OldPK) AS OldPK_max
FROM dbo.AcctSoftware;
-- Compare: Compare each _null_pct, _distinct_count, _min, _max, _sum column between source and target. Column names are identical so direct comparison is possible.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + MIN/MAX + VALUE_DIST)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: Snowflake (DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE)
-- Includes: NULL% + DISTINCT + MIN/MAX + VALUE_DIST
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN ACCTSOFTWAREID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS AcctSoftwareID_null_pct
    ROUND(100.0 * SUM(CASE WHEN SSOFTWARENAME IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS sSoftwareName_null_pct
    ROUND(100.0 * SUM(CASE WHEN BPERMANENT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS bPermanent_null_pct
    ROUND(100.0 * SUM(CASE WHEN DDELETED IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS dDeleted_null_pct
    ROUND(100.0 * SUM(CASE WHEN DUPDATED IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS dUpdated_null_pct
    ROUND(100.0 * SUM(CASE WHEN UTS IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS uTS_null_pct
    ROUND(100.0 * SUM(CASE WHEN OLDPK IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS OldPK_null_pct
    COUNT(DISTINCT ACCTSOFTWAREID) AS AcctSoftwareID_distinct_count
    COUNT(DISTINCT SSOFTWARENAME) AS sSoftwareName_distinct_count
    COUNT(DISTINCT BPERMANENT) AS bPermanent_distinct_count
    COUNT(DISTINCT DDELETED) AS dDeleted_distinct_count
    COUNT(DISTINCT DUPDATED) AS dUpdated_distinct_count
    COUNT(DISTINCT UTS) AS uTS_distinct_count
    COUNT(DISTINCT OLDPK) AS OldPK_distinct_count
    MIN(ACCTSOFTWAREID) AS AcctSoftwareID_min
    MAX(ACCTSOFTWAREID) AS AcctSoftwareID_max
    MIN(OLDPK) AS OldPK_min
    MAX(OLDPK) AS OldPK_max
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE WHERE _FIVETRAN_ACTIVE = TRUE;


-- ========================================================================
-- AI-RECOMMENDED BUSINESS RULE CHECKS
-- These are condition fragments. Run as:
--   SELECT COUNT(*) FROM <table> WHERE NOT (<condition>);
-- Any count > 0 = data quality issue.
-- ========================================================================

-- AI Recommendation: Ensure that the 'dUpdated' timestamp is not later than the 'uTS' timestamp.
-- Severity : error
-- Columns  : dUpdated, uTS
-- Condition: dUpdated <= uTS
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM dbo.AcctSoftware
WHERE NOT (dUpdated <= uTS);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (dUpdated <= uTS);


-- AI Recommendation: Verify that the 'bPermanent' column contains only valid boolean values (true or false).
-- Severity : error
-- Columns  : bPermanent
-- Condition: bPermanent IN (TRUE, FALSE)
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM dbo.AcctSoftware
WHERE NOT (bPermanent IN (TRUE, FALSE));

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (bPermanent IN (TRUE, FALSE));


-- AI Recommendation: Ensure that the 'AcctSoftwareID' column contains only non-negative integers.
-- Severity : error
-- Columns  : AcctSoftwareID
-- Condition: AcctSoftwareID >= 0
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM dbo.AcctSoftware
WHERE NOT (AcctSoftwareID >= 0);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (AcctSoftwareID >= 0);


-- AI Recommendation: Ensure that the 'dDeleted' timestamp, if present, is not earlier than the 'dUpdated' timestamp.
-- Severity : warning
-- Columns  : dDeleted, dUpdated
-- Condition: dDeleted IS NULL OR dDeleted >= dUpdated
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM dbo.AcctSoftware
WHERE NOT (dDeleted IS NULL OR dDeleted >= dUpdated);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (dDeleted IS NULL OR dDeleted >= dUpdated);


-- AI Recommendation: Ensure that the 'OldPK' column, if present, contains only non-negative integers.
-- Severity : warning
-- Columns  : OldPK
-- Condition: OldPK IS NULL OR OldPK >= 0
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM dbo.AcctSoftware
WHERE NOT (OldPK IS NULL OR OldPK >= 0);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.ACCTSOFTWARE
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (OldPK IS NULL OR OldPK >= 0);

