-- ======================================================================
-- MIGRATION VALIDATOR — Generated Validation Queries
-- Table        : addresses
-- Source       : postgresql://migration_validator_test.addresses
-- Target       : snowflake://ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES
-- Generated    : 2026-08-13T10:52:12.761982
-- Generated by : AI
-- AI Model     : gpt-4o
-- Primary Keys : NONE — No primary key detected — duplicate/missing row checks (⑨-⑭) skipped. Declare primary_keys in your batch YAML to enable them.
-- ======================================================================
-- HOW TO USE:
--   ① Run on PostgreSQL  → compare count with ②
--   ② Run on Snowflake   → compare count with ①
--   ③ Run on PostgreSQL  → export to CSV
--   ④ Run on Snowflake   → export to CSV
--   Compare ③ vs ④ row-by-row — must be IDENTICAL
--   ⑤ Run on PostgreSQL  → compare NULL % with ⑥
--   ⑥ Run on Snowflake   → compare NULL % with ⑤
--   ⑦ Run on PostgreSQL  → compare distinct counts with ⑧
--   ⑧ Run on Snowflake   → compare distinct counts with ⑦
-- ======================================================================
-- ──────────────────────────────────────────────────────────────────────
-- ① ROW COUNT — PostgreSQL (Expected: matches ②)
-- ──────────────────────────────────────────────────────────────────────
-- ① ROW COUNT: PostgreSQL (migration_validator_test.addresses)
SELECT COUNT(*) AS source_row_count
FROM migration_validator_test.addresses;

-- ──────────────────────────────────────────────────────────────────────
-- ② ROW COUNT — Snowflake  (Expected: matches ①)
-- ──────────────────────────────────────────────────────────────────────
-- ② ROW COUNT: Snowflake (ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES)
SELECT COUNT(*) AS target_row_count
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES;

-- ──────────────────────────────────────────────────────────────────────
-- ③ MAIN VALIDATION — PostgreSQL (normalised data — export CSV, compare with ④)
-- ──────────────────────────────────────────────────────────────────────
-- ③ SOURCE: PostgreSQL (migration_validator_test.addresses)
SELECT
    COALESCE(CAST(CAST(addressid AS TEXT) AS TEXT), '<<NULL>>') AS addressid_normalized,
    COALESCE(CAST(CAST(siteid AS TEXT) AS TEXT), '<<NULL>>') AS siteid_normalized,
    COALESCE(CAST(TRIM(smrmrs) AS TEXT), '<<NULL>>') AS smrmrs_normalized,
    COALESCE(CAST(TRIM(sfname) AS TEXT), '<<NULL>>') AS sfname_normalized,
    COALESCE(CAST(TRIM(smi) AS TEXT), '<<NULL>>') AS smi_normalized,
    COALESCE(CAST(TRIM(slname) AS TEXT), '<<NULL>>') AS slname_normalized,
    COALESCE(CAST(TRIM(scompany) AS TEXT), '<<NULL>>') AS scompany_normalized,
    COALESCE(CAST(TRIM(saddr1) AS TEXT), '<<NULL>>') AS saddr1_normalized,
    COALESCE(CAST(TRIM(saddr2) AS TEXT), '<<NULL>>') AS saddr2_normalized,
    COALESCE(CAST(TRIM(scity) AS TEXT), '<<NULL>>') AS scity_normalized
FROM migration_validator_test.addresses;

-- ──────────────────────────────────────────────────────────────────────
-- ④ MAIN VALIDATION — Snowflake  (normalised data — export CSV, compare with ③)
-- ──────────────────────────────────────────────────────────────────────
-- ④ TARGET: Snowflake (ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES)
SELECT
    COALESCE(CAST(CAST(ADDRESSID AS STRING) AS STRING), '<<NULL>>') AS addressid_normalized,
    COALESCE(CAST(CAST(SITEID AS STRING) AS STRING), '<<NULL>>') AS siteid_normalized,
    COALESCE(CAST(TRIM(SMRMRS) AS STRING), '<<NULL>>') AS smrmrs_normalized,
    COALESCE(CAST(TRIM(SFNAME) AS STRING), '<<NULL>>') AS sfname_normalized,
    COALESCE(CAST(TRIM(SMI) AS STRING), '<<NULL>>') AS smi_normalized,
    COALESCE(CAST(TRIM(SLNAME) AS STRING), '<<NULL>>') AS slname_normalized,
    COALESCE(CAST(TRIM(SCOMPANY) AS STRING), '<<NULL>>') AS scompany_normalized,
    COALESCE(CAST(TRIM(SADDR1) AS STRING), '<<NULL>>') AS saddr1_normalized,
    COALESCE(CAST(TRIM(SADDR2) AS STRING), '<<NULL>>') AS saddr2_normalized,
    COALESCE(CAST(TRIM(SCITY) AS STRING), '<<NULL>>') AS scity_normalized
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES;

-- ──────────────────────────────────────────────────────────────────────
-- ⑤ NULL % PER COLUMN — PostgreSQL (compare null_pct values with ⑥)
-- ──────────────────────────────────────────────────────────────────────
-- ⑤ NULL % CHECK: PostgreSQL (migration_validator_test.addresses)
SELECT
    COUNT(*) AS total_rows,
    ROUND(100.0 * SUM(CASE WHEN addressid IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS addressid_null_pct,
    ROUND(100.0 * SUM(CASE WHEN siteid IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS siteid_null_pct,
    ROUND(100.0 * SUM(CASE WHEN smrmrs IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS smrmrs_null_pct,
    ROUND(100.0 * SUM(CASE WHEN sfname IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS sfname_null_pct,
    ROUND(100.0 * SUM(CASE WHEN smi IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS smi_null_pct,
    ROUND(100.0 * SUM(CASE WHEN slname IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS slname_null_pct,
    ROUND(100.0 * SUM(CASE WHEN scompany IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS scompany_null_pct,
    ROUND(100.0 * SUM(CASE WHEN saddr1 IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS saddr1_null_pct,
    ROUND(100.0 * SUM(CASE WHEN saddr2 IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS saddr2_null_pct,
    ROUND(100.0 * SUM(CASE WHEN scity IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS scity_null_pct
FROM migration_validator_test.addresses;

-- ──────────────────────────────────────────────────────────────────────
-- ⑥ NULL % PER COLUMN — Snowflake  (compare null_pct values with ⑤)
-- ──────────────────────────────────────────────────────────────────────
-- ⑥ NULL % CHECK: Snowflake (ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES)
SELECT
    COUNT(*) AS total_rows,
    ROUND(100.0 * SUM(CASE WHEN ADDRESSID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS addressid_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SITEID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS siteid_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SMRMRS IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS smrmrs_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SFNAME IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS sfname_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SMI IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS smi_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SLNAME IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS slname_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SCOMPANY IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS scompany_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SADDR1 IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS saddr1_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SADDR2 IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS saddr2_null_pct,
    ROUND(100.0 * SUM(CASE WHEN SCITY IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS scity_null_pct
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES;

-- ──────────────────────────────────────────────────────────────────────
-- ⑦ DISTINCT VALUE COUNT — PostgreSQL (compare distinct_count with ⑧)
-- ──────────────────────────────────────────────────────────────────────
-- ⑦ DISTINCT VALUE COUNT: PostgreSQL (migration_validator_test.addresses)
-- Compare distinct counts with ⑧ — large differences indicate data drift.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT addressid) AS addressid_distinct_count,
    COUNT(DISTINCT siteid) AS siteid_distinct_count,
    COUNT(DISTINCT smrmrs) AS smrmrs_distinct_count,
    COUNT(DISTINCT sfname) AS sfname_distinct_count,
    COUNT(DISTINCT smi) AS smi_distinct_count,
    COUNT(DISTINCT slname) AS slname_distinct_count,
    COUNT(DISTINCT scompany) AS scompany_distinct_count,
    COUNT(DISTINCT saddr1) AS saddr1_distinct_count,
    COUNT(DISTINCT saddr2) AS saddr2_distinct_count,
    COUNT(DISTINCT scity) AS scity_distinct_count
FROM migration_validator_test.addresses;

-- ──────────────────────────────────────────────────────────────────────
-- ⑧ DISTINCT VALUE COUNT — Snowflake  (compare distinct_count with ⑦)
-- ──────────────────────────────────────────────────────────────────────
-- ⑧ DISTINCT VALUE COUNT: Snowflake (ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES)
-- Compare distinct counts with ⑦ — large differences indicate data drift.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ADDRESSID) AS addressid_distinct_count,
    COUNT(DISTINCT SITEID) AS siteid_distinct_count,
    COUNT(DISTINCT SMRMRS) AS smrmrs_distinct_count,
    COUNT(DISTINCT SFNAME) AS sfname_distinct_count,
    COUNT(DISTINCT SMI) AS smi_distinct_count,
    COUNT(DISTINCT SLNAME) AS slname_distinct_count,
    COUNT(DISTINCT SCOMPANY) AS scompany_distinct_count,
    COUNT(DISTINCT SADDR1) AS saddr1_distinct_count,
    COUNT(DISTINCT SADDR2) AS saddr2_distinct_count,
    COUNT(DISTINCT SCITY) AS scity_distinct_count
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES;
