-- ========================================================================
-- DYNAMIC MIGRATION VALIDATOR — Generated Validation Suite
-- Source       : migration_validator_test.addresses
-- Target       : ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES
-- Generated    : 2026-08-13T10:52:17.424552
-- Generated by : AI
-- AI Model     : gpt-4o
-- Total checks : 3 query pair(s)
-- Fivetran     : NO
-- ========================================================================

-- HOW TO USE:
-- 1. Run each SOURCE query on PostgreSQL, each TARGET on Snowflake.
-- 2. Compare the result sets as instructed in the comparison note.
-- 3. Any row-count difference OR value mismatch = FAIL.
-- 4. Aggregate queries (MIN/MAX/SUM) are combined — compare columns.
-- ========================================================================

-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ① ROW COUNT: PostgreSQL (migration_validator_test.addresses)
SELECT COUNT(*) AS source_row_count
FROM migration_validator_test.addresses;
-- Compare: source_row_count must equal target_row_count

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ② ROW COUNT: Snowflake (ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES)
SELECT COUNT(*) AS target_row_count
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ③ SOURCE: PostgreSQL (migration_validator_test.addresses)
SELECT
    COALESCE(CAST(CAST(addressid AS TEXT) AS TEXT), '<<NULL>>') AS addressid_normalized,
    COALESCE(CAST(CAST(siteid AS TEXT) AS TEXT), '<<NULL>>') AS siteid_normalized,
    COALESCE(CAST(TRIM(smrmrs) AS TEXT), '<<NULL>>') AS smrmrs_normalized,
    COALESCE(CAST(TRIM(sfname) AS TEXT), '<<NULL>>') AS sfname_normalized,
    COALESCE(CAST(TRIM(smi) AS TEXT), '<<NULL>>') AS smi_normalized,
    COALESCE(CAST(TRIM(slname) AS TEXT), '<<NULL>>') AS slname_normalized,
    COALESCE(CAST(TRIM(scompany) AS TEXT), '<<NULL>>') AS scompany_normalized,
    COALESCE(CAST(TRIM(saddr1) AS TEXT), '<<NULL>>') AS saddr1_normalized,
    COALESCE(CAST(TRIM(saddr2) AS TEXT), '<<NULL>>') AS saddr2_normalized,
    COALESCE(CAST(TRIM(scity) AS TEXT), '<<NULL>>') AS scity_normalized
FROM migration_validator_test.addresses;
-- Compare: Export both to CSV. Compare row-by-row — must be identical. All values are normalised so comparison is type-safe.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ④ TARGET: Snowflake (ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES)
SELECT
    COALESCE(CAST(CAST(ADDRESSID AS STRING) AS STRING), '<<NULL>>') AS addressid_normalized,
    COALESCE(CAST(CAST(SITEID AS STRING) AS STRING), '<<NULL>>') AS siteid_normalized,
    COALESCE(CAST(TRIM(SMRMRS) AS STRING), '<<NULL>>') AS smrmrs_normalized,
    COALESCE(CAST(TRIM(SFNAME) AS STRING), '<<NULL>>') AS sfname_normalized,
    COALESCE(CAST(TRIM(SMI) AS STRING), '<<NULL>>') AS smi_normalized,
    COALESCE(CAST(TRIM(SLNAME) AS STRING), '<<NULL>>') AS slname_normalized,
    COALESCE(CAST(TRIM(SCOMPANY) AS STRING), '<<NULL>>') AS scompany_normalized,
    COALESCE(CAST(TRIM(SADDR1) AS STRING), '<<NULL>>') AS saddr1_normalized,
    COALESCE(CAST(TRIM(SADDR2) AS STRING), '<<NULL>>') AS saddr2_normalized,
    COALESCE(CAST(TRIM(SCITY) AS STRING), '<<NULL>>') AS scity_normalized
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + MIN/MAX)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: PostgreSQL (migration_validator_test.addresses)
-- Includes: NULL% + DISTINCT + MIN/MAX
-- One scan replaces 3 separate aggregate query types.
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN addressid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS addressid_null_pct
    ROUND(100.0 * SUM(CASE WHEN siteid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS siteid_null_pct
    ROUND(100.0 * SUM(CASE WHEN smrmrs IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS smrmrs_null_pct
    ROUND(100.0 * SUM(CASE WHEN sfname IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS sfname_null_pct
    ROUND(100.0 * SUM(CASE WHEN smi IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS smi_null_pct
    ROUND(100.0 * SUM(CASE WHEN slname IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS slname_null_pct
    ROUND(100.0 * SUM(CASE WHEN scompany IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS scompany_null_pct
    ROUND(100.0 * SUM(CASE WHEN saddr1 IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS saddr1_null_pct
    ROUND(100.0 * SUM(CASE WHEN saddr2 IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS saddr2_null_pct
    ROUND(100.0 * SUM(CASE WHEN scity IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS scity_null_pct
    COUNT(DISTINCT addressid) AS addressid_distinct_count
    COUNT(DISTINCT siteid) AS siteid_distinct_count
    COUNT(DISTINCT smrmrs) AS smrmrs_distinct_count
    COUNT(DISTINCT sfname) AS sfname_distinct_count
    COUNT(DISTINCT smi) AS smi_distinct_count
    COUNT(DISTINCT slname) AS slname_distinct_count
    COUNT(DISTINCT scompany) AS scompany_distinct_count
    COUNT(DISTINCT saddr1) AS saddr1_distinct_count
    COUNT(DISTINCT saddr2) AS saddr2_distinct_count
    COUNT(DISTINCT scity) AS scity_distinct_count
    MIN(addressid) AS addressid_min
    MAX(addressid) AS addressid_max
    MIN(siteid) AS siteid_min
    MAX(siteid) AS siteid_max
FROM migration_validator_test.addresses;
-- Compare: Compare each _null_pct, _distinct_count, _min, _max, _sum column between source and target. Column names are identical so direct comparison is possible.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + MIN/MAX)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: Snowflake (ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES)
-- Includes: NULL% + DISTINCT + MIN/MAX
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN ADDRESSID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS addressid_null_pct
    ROUND(100.0 * SUM(CASE WHEN SITEID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS siteid_null_pct
    ROUND(100.0 * SUM(CASE WHEN SMRMRS IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS smrmrs_null_pct
    ROUND(100.0 * SUM(CASE WHEN SFNAME IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS sfname_null_pct
    ROUND(100.0 * SUM(CASE WHEN SMI IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS smi_null_pct
    ROUND(100.0 * SUM(CASE WHEN SLNAME IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS slname_null_pct
    ROUND(100.0 * SUM(CASE WHEN SCOMPANY IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS scompany_null_pct
    ROUND(100.0 * SUM(CASE WHEN SADDR1 IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS saddr1_null_pct
    ROUND(100.0 * SUM(CASE WHEN SADDR2 IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS saddr2_null_pct
    ROUND(100.0 * SUM(CASE WHEN SCITY IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS scity_null_pct
    COUNT(DISTINCT ADDRESSID) AS addressid_distinct_count
    COUNT(DISTINCT SITEID) AS siteid_distinct_count
    COUNT(DISTINCT SMRMRS) AS smrmrs_distinct_count
    COUNT(DISTINCT SFNAME) AS sfname_distinct_count
    COUNT(DISTINCT SMI) AS smi_distinct_count
    COUNT(DISTINCT SLNAME) AS slname_distinct_count
    COUNT(DISTINCT SCOMPANY) AS scompany_distinct_count
    COUNT(DISTINCT SADDR1) AS saddr1_distinct_count
    COUNT(DISTINCT SADDR2) AS saddr2_distinct_count
    COUNT(DISTINCT SCITY) AS scity_distinct_count
    MIN(ADDRESSID) AS addressid_min
    MAX(ADDRESSID) AS addressid_max
    MIN(SITEID) AS siteid_min
    MAX(SITEID) AS siteid_max
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES;


-- ========================================================================
-- AI-RECOMMENDED BUSINESS RULE CHECKS
-- These are condition fragments. Run as:
--   SELECT COUNT(*) FROM <table> WHERE NOT (<condition>);
-- Any count > 0 = data quality issue.
-- ========================================================================

-- AI Recommendation: Ensure that addressid values are positive.
-- Severity : error
-- Columns  : addressid
-- Condition: addressid >= 0
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM migration_validator_test.addresses
WHERE NOT (addressid >= 0);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES
WHERE NOT (addressid >= 0);


-- AI Recommendation: Ensure that siteid values are positive.
-- Severity : error
-- Columns  : siteid
-- Condition: siteid >= 0
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM migration_validator_test.addresses
WHERE NOT (siteid >= 0);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES
WHERE NOT (siteid >= 0);


-- AI Recommendation: Ensure that saddr1 is not empty if saddr2 is provided.
-- Severity : warning
-- Columns  : saddr1, saddr2
-- Condition: saddr2 IS NULL OR saddr1 IS NOT NULL
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM migration_validator_test.addresses
WHERE NOT (saddr2 IS NULL OR saddr1 IS NOT NULL);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES
WHERE NOT (saddr2 IS NULL OR saddr1 IS NOT NULL);


-- AI Recommendation: Ensure that scity is not empty if saddr1 is provided.
-- Severity : warning
-- Columns  : scity, saddr1
-- Condition: saddr1 IS NULL OR scity IS NOT NULL
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM migration_validator_test.addresses
WHERE NOT (saddr1 IS NULL OR scity IS NOT NULL);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES
WHERE NOT (saddr1 IS NULL OR scity IS NOT NULL);


-- AI Recommendation: Ensure that smi (middle initial) is either NULL or a single character.
-- Severity : warning
-- Columns  : smi
-- Condition: smi IS NULL OR char_length(smi) = 1
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM migration_validator_test.addresses
WHERE NOT (smi IS NULL OR char_length(smi) = 1);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM ATHENA_DATABASE_SNOWFLAKE.ATHENA_SCHEMA.ADDRESSES
WHERE NOT (smi IS NULL OR length(smi) = 1);

