-- ========================================================================
-- DYNAMIC MIGRATION VALIDATOR — Generated Validation Suite
-- Source       : public.events
-- Target       : dev_edge_bronze.storedge_fms_public.EVENTS
-- Generated    : 2026-08-10T18:02:24.889377
-- Generated by : AI
-- AI Model     : gpt-4o
-- Total checks : 4 query pair(s)
-- Fivetran     : YES — WHERE _FIVETRAN_ACTIVE = TRUE
-- ========================================================================

-- HOW TO USE:
-- 1. Run each SOURCE query on PostgreSQL, each TARGET on Snowflake.
-- 2. Compare the result sets as instructed in the comparison note.
-- 3. Any row-count difference OR value mismatch = FAIL.
-- 4. Aggregate queries (MIN/MAX/SUM) are combined — compare columns.
-- ========================================================================

-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ① ROW COUNT: PostgreSQL (public.events)
SELECT COUNT(*) AS source_row_count
FROM public.events;
-- Compare: source_row_count must equal target_row_count

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ② ROW COUNT: Snowflake (dev_edge_bronze.storedge_fms_public.EVENTS)
SELECT COUNT(*) AS target_row_count
FROM dev_edge_bronze.storedge_fms_public.EVENTS WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ③ SOURCE: PostgreSQL (public.events)
SELECT
    COALESCE(CAST(CAST(id AS TEXT) AS TEXT), '<<NULL>>') AS id_normalized,
    COALESCE(CAST(TRIM(type) AS TEXT), '<<NULL>>') AS type_normalized,
    COALESCE(CAST(TRIM(CAST(data AS TEXT)) AS TEXT), '<<NULL>>') AS data_normalized,
    COALESCE(CAST(CASE WHEN needs_followup = true  THEN '1' WHEN needs_followup = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS needs_followup_normalized,
    COALESCE(CAST(TO_CHAR(needs_followup_by, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS needs_followup_by_normalized,
    COALESCE(CAST(TO_CHAR(followup_date, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS followup_date_normalized,
    COALESCE(CAST(CASE WHEN resolved = true  THEN '1' WHEN resolved = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS resolved_normalized,
    COALESCE(CAST(CAST(created_by_id AS TEXT) AS TEXT), '<<NULL>>') AS created_by_id_normalized,
    COALESCE(CAST(CAST(updated_by_id AS TEXT) AS TEXT), '<<NULL>>') AS updated_by_id_normalized,
    COALESCE(CAST(CAST(unit_id AS TEXT) AS TEXT), '<<NULL>>') AS unit_id_normalized,
    COALESCE(CAST(CAST(tenant_id AS TEXT) AS TEXT), '<<NULL>>') AS tenant_id_normalized,
    COALESCE(CAST(CAST(source_id AS TEXT) AS TEXT), '<<NULL>>') AS source_id_normalized,
    COALESCE(CAST(CAST(facility_id AS TEXT) AS TEXT), '<<NULL>>') AS facility_id_normalized,
    COALESCE(CAST(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS created_at_normalized,
    COALESCE(CAST(TO_CHAR(updated_at, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS updated_at_normalized,
    COALESCE(CAST(CAST(parent_event_id AS TEXT) AS TEXT), '<<NULL>>') AS parent_event_id_normalized,
    COALESCE(CAST(CAST(related_object_id AS TEXT) AS TEXT), '<<NULL>>') AS related_object_id_normalized,
    COALESCE(CAST(TRIM(related_object_type) AS TEXT), '<<NULL>>') AS related_object_type_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(uuid AS TEXT))) AS TEXT), '<<NULL>>') AS uuid_normalized,
    COALESCE(CAST(TRIM(status) AS TEXT), '<<NULL>>') AS status_normalized,
    COALESCE(CAST(CASE WHEN important_task = true  THEN '1' WHEN important_task = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS important_task_normalized,
    COALESCE(CAST(TO_CHAR(resolved_on, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS resolved_on_normalized,
    COALESCE(CAST(TRIM(created_by_type) AS TEXT), '<<NULL>>') AS created_by_type_normalized,
    COALESCE(CAST(TRIM(updated_by_type) AS TEXT), '<<NULL>>') AS updated_by_type_normalized,
    COALESCE(CAST(CAST(ledger_id AS TEXT) AS TEXT), '<<NULL>>') AS ledger_id_normalized,
    COALESCE(CAST(CAST(lead_id AS TEXT) AS TEXT), '<<NULL>>') AS lead_id_normalized,
    COALESCE(CAST(CAST(support_case_id AS TEXT) AS TEXT), '<<NULL>>') AS support_case_id_normalized,
    COALESCE(CAST(CAST(attachment_id AS TEXT) AS TEXT), '<<NULL>>') AS attachment_id_normalized,
    COALESCE(CAST(TRIM(action_item) AS TEXT), '<<NULL>>') AS action_item_normalized,
    COALESCE(CAST(CAST(ledger_delinquency_id AS TEXT) AS TEXT), '<<NULL>>') AS ledger_delinquency_id_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(company_uuid AS TEXT))) AS TEXT), '<<NULL>>') AS company_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(facility_uuid AS TEXT))) AS TEXT), '<<NULL>>') AS facility_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(tenant_uuid AS TEXT))) AS TEXT), '<<NULL>>') AS tenant_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(ledger_uuid AS TEXT))) AS TEXT), '<<NULL>>') AS ledger_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(unit_uuid AS TEXT))) AS TEXT), '<<NULL>>') AS unit_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(lead_uuid AS TEXT))) AS TEXT), '<<NULL>>') AS lead_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(related_object_uuid AS TEXT))) AS TEXT), '<<NULL>>') AS related_object_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(client_application_id AS TEXT))) AS TEXT), '<<NULL>>') AS client_application_id_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(payment_intent_id AS TEXT))) AS TEXT), '<<NULL>>') AS payment_intent_id_normalized
FROM public.events;
-- Compare: Export both to CSV. Compare row-by-row — must be identical. All values are normalised so comparison is type-safe.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ④ TARGET: Snowflake (dev_edge_bronze.storedge_fms_public.EVENTS)
SELECT
    COALESCE(CAST(CAST(ID AS STRING) AS STRING), '<<NULL>>') AS id_normalized,
    COALESCE(CAST(TRIM(TYPE) AS STRING), '<<NULL>>') AS type_normalized,
    COALESCE(CAST(TRIM(DATA) AS STRING), '<<NULL>>') AS data_normalized,
    COALESCE(CAST(CASE WHEN NEEDS_FOLLOWUP = TRUE  THEN '1' WHEN NEEDS_FOLLOWUP = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS needs_followup_normalized,
    COALESCE(CAST(TO_VARCHAR(NEEDS_FOLLOWUP_BY, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS needs_followup_by_normalized,
    COALESCE(CAST(TO_VARCHAR(FOLLOWUP_DATE, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS followup_date_normalized,
    COALESCE(CAST(CASE WHEN RESOLVED = TRUE  THEN '1' WHEN RESOLVED = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS resolved_normalized,
    COALESCE(CAST(CAST(CREATED_BY_ID AS STRING) AS STRING), '<<NULL>>') AS created_by_id_normalized,
    COALESCE(CAST(CAST(UPDATED_BY_ID AS STRING) AS STRING), '<<NULL>>') AS updated_by_id_normalized,
    COALESCE(CAST(CAST(UNIT_ID AS STRING) AS STRING), '<<NULL>>') AS unit_id_normalized,
    COALESCE(CAST(CAST(TENANT_ID AS STRING) AS STRING), '<<NULL>>') AS tenant_id_normalized,
    COALESCE(CAST(CAST(SOURCE_ID AS STRING) AS STRING), '<<NULL>>') AS source_id_normalized,
    COALESCE(CAST(CAST(FACILITY_ID AS STRING) AS STRING), '<<NULL>>') AS facility_id_normalized,
    COALESCE(CAST(TO_VARCHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS created_at_normalized,
    COALESCE(CAST(TO_VARCHAR(UPDATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS updated_at_normalized,
    COALESCE(CAST(CAST(PARENT_EVENT_ID AS STRING) AS STRING), '<<NULL>>') AS parent_event_id_normalized,
    COALESCE(CAST(CAST(RELATED_OBJECT_ID AS STRING) AS STRING), '<<NULL>>') AS related_object_id_normalized,
    COALESCE(CAST(TRIM(RELATED_OBJECT_TYPE) AS STRING), '<<NULL>>') AS related_object_type_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(UUID AS STRING))) AS STRING), '<<NULL>>') AS uuid_normalized,
    COALESCE(CAST(TRIM(STATUS) AS STRING), '<<NULL>>') AS status_normalized,
    COALESCE(CAST(CASE WHEN IMPORTANT_TASK = TRUE  THEN '1' WHEN IMPORTANT_TASK = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS important_task_normalized,
    COALESCE(CAST(TO_VARCHAR(RESOLVED_ON, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS resolved_on_normalized,
    COALESCE(CAST(TRIM(CREATED_BY_TYPE) AS STRING), '<<NULL>>') AS created_by_type_normalized,
    COALESCE(CAST(TRIM(UPDATED_BY_TYPE) AS STRING), '<<NULL>>') AS updated_by_type_normalized,
    COALESCE(CAST(CAST(LEDGER_ID AS STRING) AS STRING), '<<NULL>>') AS ledger_id_normalized,
    COALESCE(CAST(CAST(LEAD_ID AS STRING) AS STRING), '<<NULL>>') AS lead_id_normalized,
    COALESCE(CAST(CAST(SUPPORT_CASE_ID AS STRING) AS STRING), '<<NULL>>') AS support_case_id_normalized,
    COALESCE(CAST(CAST(ATTACHMENT_ID AS STRING) AS STRING), '<<NULL>>') AS attachment_id_normalized,
    COALESCE(CAST(TRIM(ACTION_ITEM) AS STRING), '<<NULL>>') AS action_item_normalized,
    COALESCE(CAST(CAST(LEDGER_DELINQUENCY_ID AS STRING) AS STRING), '<<NULL>>') AS ledger_delinquency_id_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(COMPANY_UUID AS STRING))) AS STRING), '<<NULL>>') AS company_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(FACILITY_UUID AS STRING))) AS STRING), '<<NULL>>') AS facility_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(TENANT_UUID AS STRING))) AS STRING), '<<NULL>>') AS tenant_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(LEDGER_UUID AS STRING))) AS STRING), '<<NULL>>') AS ledger_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(UNIT_UUID AS STRING))) AS STRING), '<<NULL>>') AS unit_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(LEAD_UUID AS STRING))) AS STRING), '<<NULL>>') AS lead_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(RELATED_OBJECT_UUID AS STRING))) AS STRING), '<<NULL>>') AS related_object_uuid_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(CLIENT_APPLICATION_ID AS STRING))) AS STRING), '<<NULL>>') AS client_application_id_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(PAYMENT_INTENT_ID AS STRING))) AS STRING), '<<NULL>>') AS payment_intent_id_normalized
FROM dev_edge_bronze.storedge_fms_public.EVENTS WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + VALUE_DIST)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: PostgreSQL (public.events)
-- Includes: NULL% + DISTINCT + VALUE_DIST
-- One scan replaces 3 separate aggregate query types.
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS id_null_pct
    ROUND(100.0 * SUM(CASE WHEN type IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS type_null_pct
    ROUND(100.0 * SUM(CASE WHEN needs_followup IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS needs_followup_null_pct
    ROUND(100.0 * SUM(CASE WHEN needs_followup_by IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS needs_followup_by_null_pct
    ROUND(100.0 * SUM(CASE WHEN followup_date IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS followup_date_null_pct
    ROUND(100.0 * SUM(CASE WHEN resolved IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS resolved_null_pct
    ROUND(100.0 * SUM(CASE WHEN created_by_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS created_by_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN updated_by_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS updated_by_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN unit_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS unit_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN tenant_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS tenant_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN source_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS source_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN facility_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS facility_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN created_at IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS created_at_null_pct
    ROUND(100.0 * SUM(CASE WHEN updated_at IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS updated_at_null_pct
    ROUND(100.0 * SUM(CASE WHEN parent_event_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS parent_event_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN related_object_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS related_object_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN related_object_type IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS related_object_type_null_pct
    ROUND(100.0 * SUM(CASE WHEN uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN status IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS status_null_pct
    ROUND(100.0 * SUM(CASE WHEN important_task IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS important_task_null_pct
    ROUND(100.0 * SUM(CASE WHEN resolved_on IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS resolved_on_null_pct
    ROUND(100.0 * SUM(CASE WHEN created_by_type IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS created_by_type_null_pct
    ROUND(100.0 * SUM(CASE WHEN updated_by_type IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS updated_by_type_null_pct
    ROUND(100.0 * SUM(CASE WHEN ledger_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS ledger_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN lead_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS lead_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN support_case_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS support_case_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN attachment_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS attachment_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN action_item IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS action_item_null_pct
    ROUND(100.0 * SUM(CASE WHEN ledger_delinquency_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS ledger_delinquency_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN company_uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS company_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN facility_uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS facility_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN tenant_uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS tenant_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN ledger_uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS ledger_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN unit_uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS unit_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN lead_uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS lead_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN related_object_uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS related_object_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN client_application_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS client_application_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN payment_intent_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS payment_intent_id_null_pct
    COUNT(DISTINCT id) AS id_distinct_count
    COUNT(DISTINCT type) AS type_distinct_count
    COUNT(DISTINCT needs_followup) AS needs_followup_distinct_count
    COUNT(DISTINCT needs_followup_by) AS needs_followup_by_distinct_count
    COUNT(DISTINCT followup_date) AS followup_date_distinct_count
    COUNT(DISTINCT resolved) AS resolved_distinct_count
    COUNT(DISTINCT created_by_id) AS created_by_id_distinct_count
    COUNT(DISTINCT updated_by_id) AS updated_by_id_distinct_count
    COUNT(DISTINCT unit_id) AS unit_id_distinct_count
    COUNT(DISTINCT tenant_id) AS tenant_id_distinct_count
    COUNT(DISTINCT source_id) AS source_id_distinct_count
    COUNT(DISTINCT facility_id) AS facility_id_distinct_count
    COUNT(DISTINCT created_at) AS created_at_distinct_count
    COUNT(DISTINCT updated_at) AS updated_at_distinct_count
    COUNT(DISTINCT parent_event_id) AS parent_event_id_distinct_count
    COUNT(DISTINCT related_object_id) AS related_object_id_distinct_count
    COUNT(DISTINCT related_object_type) AS related_object_type_distinct_count
    COUNT(DISTINCT uuid) AS uuid_distinct_count
    COUNT(DISTINCT status) AS status_distinct_count
    COUNT(DISTINCT important_task) AS important_task_distinct_count
    COUNT(DISTINCT resolved_on) AS resolved_on_distinct_count
    COUNT(DISTINCT created_by_type) AS created_by_type_distinct_count
    COUNT(DISTINCT updated_by_type) AS updated_by_type_distinct_count
    COUNT(DISTINCT ledger_id) AS ledger_id_distinct_count
    COUNT(DISTINCT lead_id) AS lead_id_distinct_count
    COUNT(DISTINCT support_case_id) AS support_case_id_distinct_count
    COUNT(DISTINCT attachment_id) AS attachment_id_distinct_count
    COUNT(DISTINCT action_item) AS action_item_distinct_count
    COUNT(DISTINCT ledger_delinquency_id) AS ledger_delinquency_id_distinct_count
    COUNT(DISTINCT company_uuid) AS company_uuid_distinct_count
    COUNT(DISTINCT facility_uuid) AS facility_uuid_distinct_count
    COUNT(DISTINCT tenant_uuid) AS tenant_uuid_distinct_count
    COUNT(DISTINCT ledger_uuid) AS ledger_uuid_distinct_count
    COUNT(DISTINCT unit_uuid) AS unit_uuid_distinct_count
    COUNT(DISTINCT lead_uuid) AS lead_uuid_distinct_count
    COUNT(DISTINCT related_object_uuid) AS related_object_uuid_distinct_count
    COUNT(DISTINCT client_application_id) AS client_application_id_distinct_count
    COUNT(DISTINCT payment_intent_id) AS payment_intent_id_distinct_count
FROM public.events;
-- Compare: Compare each _null_pct, _distinct_count, _min, _max, _sum column between source and target. Column names are identical so direct comparison is possible.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + VALUE_DIST)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: Snowflake (dev_edge_bronze.storedge_fms_public.EVENTS)
-- Includes: NULL% + DISTINCT + VALUE_DIST
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS id_null_pct
    ROUND(100.0 * SUM(CASE WHEN TYPE IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS type_null_pct
    ROUND(100.0 * SUM(CASE WHEN NEEDS_FOLLOWUP IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS needs_followup_null_pct
    ROUND(100.0 * SUM(CASE WHEN NEEDS_FOLLOWUP_BY IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS needs_followup_by_null_pct
    ROUND(100.0 * SUM(CASE WHEN FOLLOWUP_DATE IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS followup_date_null_pct
    ROUND(100.0 * SUM(CASE WHEN RESOLVED IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS resolved_null_pct
    ROUND(100.0 * SUM(CASE WHEN CREATED_BY_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS created_by_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN UPDATED_BY_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS updated_by_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN UNIT_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS unit_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN TENANT_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS tenant_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN SOURCE_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS source_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN FACILITY_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS facility_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN CREATED_AT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS created_at_null_pct
    ROUND(100.0 * SUM(CASE WHEN UPDATED_AT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS updated_at_null_pct
    ROUND(100.0 * SUM(CASE WHEN PARENT_EVENT_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS parent_event_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN RELATED_OBJECT_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS related_object_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN RELATED_OBJECT_TYPE IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS related_object_type_null_pct
    ROUND(100.0 * SUM(CASE WHEN UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN STATUS IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS status_null_pct
    ROUND(100.0 * SUM(CASE WHEN IMPORTANT_TASK IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS important_task_null_pct
    ROUND(100.0 * SUM(CASE WHEN RESOLVED_ON IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS resolved_on_null_pct
    ROUND(100.0 * SUM(CASE WHEN CREATED_BY_TYPE IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS created_by_type_null_pct
    ROUND(100.0 * SUM(CASE WHEN UPDATED_BY_TYPE IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS updated_by_type_null_pct
    ROUND(100.0 * SUM(CASE WHEN LEDGER_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS ledger_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN LEAD_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS lead_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN SUPPORT_CASE_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS support_case_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN ATTACHMENT_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS attachment_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN ACTION_ITEM IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS action_item_null_pct
    ROUND(100.0 * SUM(CASE WHEN LEDGER_DELINQUENCY_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS ledger_delinquency_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN COMPANY_UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS company_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN FACILITY_UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS facility_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN TENANT_UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS tenant_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN LEDGER_UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS ledger_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN UNIT_UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS unit_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN LEAD_UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS lead_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN RELATED_OBJECT_UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS related_object_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN CLIENT_APPLICATION_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS client_application_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN PAYMENT_INTENT_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS payment_intent_id_null_pct
    COUNT(DISTINCT ID) AS id_distinct_count
    COUNT(DISTINCT TYPE) AS type_distinct_count
    COUNT(DISTINCT NEEDS_FOLLOWUP) AS needs_followup_distinct_count
    COUNT(DISTINCT NEEDS_FOLLOWUP_BY) AS needs_followup_by_distinct_count
    COUNT(DISTINCT FOLLOWUP_DATE) AS followup_date_distinct_count
    COUNT(DISTINCT RESOLVED) AS resolved_distinct_count
    COUNT(DISTINCT CREATED_BY_ID) AS created_by_id_distinct_count
    COUNT(DISTINCT UPDATED_BY_ID) AS updated_by_id_distinct_count
    COUNT(DISTINCT UNIT_ID) AS unit_id_distinct_count
    COUNT(DISTINCT TENANT_ID) AS tenant_id_distinct_count
    COUNT(DISTINCT SOURCE_ID) AS source_id_distinct_count
    COUNT(DISTINCT FACILITY_ID) AS facility_id_distinct_count
    COUNT(DISTINCT CREATED_AT) AS created_at_distinct_count
    COUNT(DISTINCT UPDATED_AT) AS updated_at_distinct_count
    COUNT(DISTINCT PARENT_EVENT_ID) AS parent_event_id_distinct_count
    COUNT(DISTINCT RELATED_OBJECT_ID) AS related_object_id_distinct_count
    COUNT(DISTINCT RELATED_OBJECT_TYPE) AS related_object_type_distinct_count
    COUNT(DISTINCT UUID) AS uuid_distinct_count
    COUNT(DISTINCT STATUS) AS status_distinct_count
    COUNT(DISTINCT IMPORTANT_TASK) AS important_task_distinct_count
    COUNT(DISTINCT RESOLVED_ON) AS resolved_on_distinct_count
    COUNT(DISTINCT CREATED_BY_TYPE) AS created_by_type_distinct_count
    COUNT(DISTINCT UPDATED_BY_TYPE) AS updated_by_type_distinct_count
    COUNT(DISTINCT LEDGER_ID) AS ledger_id_distinct_count
    COUNT(DISTINCT LEAD_ID) AS lead_id_distinct_count
    COUNT(DISTINCT SUPPORT_CASE_ID) AS support_case_id_distinct_count
    COUNT(DISTINCT ATTACHMENT_ID) AS attachment_id_distinct_count
    COUNT(DISTINCT ACTION_ITEM) AS action_item_distinct_count
    COUNT(DISTINCT LEDGER_DELINQUENCY_ID) AS ledger_delinquency_id_distinct_count
    COUNT(DISTINCT COMPANY_UUID) AS company_uuid_distinct_count
    COUNT(DISTINCT FACILITY_UUID) AS facility_uuid_distinct_count
    COUNT(DISTINCT TENANT_UUID) AS tenant_uuid_distinct_count
    COUNT(DISTINCT LEDGER_UUID) AS ledger_uuid_distinct_count
    COUNT(DISTINCT UNIT_UUID) AS unit_uuid_distinct_count
    COUNT(DISTINCT LEAD_UUID) AS lead_uuid_distinct_count
    COUNT(DISTINCT RELATED_OBJECT_UUID) AS related_object_uuid_distinct_count
    COUNT(DISTINCT CLIENT_APPLICATION_ID) AS client_application_id_distinct_count
    COUNT(DISTINCT PAYMENT_INTENT_ID) AS payment_intent_id_distinct_count
FROM dev_edge_bronze.storedge_fms_public.EVENTS WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ⑬ / ⑭ — Duplicate Check (Business Key)
-- ────────────────────────────────────────────────────────────────────────
-- ⑬ DUPLICATE CHECK: PostgreSQL (public.events)
-- Expect: 0 rows returned. Any row = duplicate business key.
SELECT
    id,
    COUNT(*) AS duplicate_count
FROM public.events
GROUP BY id
HAVING COUNT(*) > 1;
-- Compare: Both queries should return 0 rows. Any row means duplicate business-key values exist.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ⑬ / ⑭ — Duplicate Check (Business Key)
-- ────────────────────────────────────────────────────────────────────────
-- ⑭ DUPLICATE CHECK: Snowflake (dev_edge_bronze.storedge_fms_public.EVENTS)
-- Expect: 0 rows returned. Any row = duplicate business key.
SELECT
    ID,
    COUNT(*) AS duplicate_count
FROM dev_edge_bronze.storedge_fms_public.EVENTS
WHERE _FIVETRAN_ACTIVE = TRUE
GROUP BY ID
HAVING COUNT(*) > 1;


-- ========================================================================
-- AI-RECOMMENDED BUSINESS RULE CHECKS
-- These are condition fragments. Run as:
--   SELECT COUNT(*) FROM <table> WHERE NOT (<condition>);
-- Any count > 0 = data quality issue.
-- ========================================================================

-- AI Recommendation: If 'needs_followup' is true, 'needs_followup_by' should not be NULL.
-- Severity : error
-- Columns  : needs_followup, needs_followup_by
-- Condition: needs_followup = TRUE AND needs_followup_by IS NULL
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.events
WHERE NOT (needs_followup = TRUE AND needs_followup_by IS NULL);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.EVENTS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (needs_followup = TRUE AND needs_followup_by IS NULL);


-- AI Recommendation: 'resolved_on' should not be earlier than 'created_at'.
-- Severity : error
-- Columns  : resolved_on, created_at
-- Condition: resolved_on < created_at
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.events
WHERE NOT (resolved_on < created_at);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.EVENTS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (resolved_on < created_at);


-- AI Recommendation: 'parent_event_id' should not reference the same 'id'.
-- Severity : error
-- Columns  : id, parent_event_id
-- Condition: id = parent_event_id
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.events
WHERE NOT (id = parent_event_id);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.EVENTS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (id = parent_event_id);


-- AI Recommendation: If 'related_object_id' is not NULL, 'related_object_type' should not be NULL.
-- Severity : error
-- Columns  : related_object_id, related_object_type
-- Condition: related_object_id IS NOT NULL AND related_object_type IS NULL
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.events
WHERE NOT (related_object_id IS NOT NULL AND related_object_type IS NULL);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.EVENTS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (related_object_id IS NOT NULL AND related_object_type IS NULL);


-- AI Recommendation: 'uuid' values should be unique across all rows.
-- Severity : error
-- Columns  : uuid
-- Condition: COUNT(uuid) OVER (PARTITION BY uuid) > 1
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.events
WHERE NOT (COUNT(uuid) OVER (PARTITION BY uuid) > 1);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.EVENTS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (COUNT(uuid) OVER (PARTITION BY uuid) > 1);

