-- ======================================================================
-- MIGRATION VALIDATOR — Generated Validation Queries
-- Table        : general_ledger_line_items
-- Source       : postgresql://public.general_ledger_line_items
-- Target       : snowflake://dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
-- Generated    : 2026-08-10T20:04:19.708711
-- Generated by : AI
-- AI Model     : gpt-4o
-- ======================================================================
-- HOW TO USE:
--   ① Run on PostgreSQL  → compare count with ②
--   ② Run on Snowflake   → compare count with ①
--   ③ Run on PostgreSQL  → export to CSV
--   ④ Run on Snowflake   → export to CSV
--   Compare ③ vs ④ row-by-row — must be IDENTICAL
--   ⑤ Run on PostgreSQL  → compare NULL % with ⑥
--   ⑥ Run on Snowflake   → compare NULL % with ⑤
--   ⑦ Run on PostgreSQL  → compare distinct counts with ⑧
--   ⑧ Run on Snowflake   → compare distinct counts with ⑦
-- ======================================================================
-- ──────────────────────────────────────────────────────────────────────
-- ① ROW COUNT — PostgreSQL (Expected: matches ②)
-- ──────────────────────────────────────────────────────────────────────
-- ① ROW COUNT: PostgreSQL (public.general_ledger_line_items)
SELECT COUNT(*) AS source_row_count
FROM public.general_ledger_line_items;

-- ──────────────────────────────────────────────────────────────────────
-- ② ROW COUNT — Snowflake  (Expected: matches ①)
-- ──────────────────────────────────────────────────────────────────────
-- ② ROW COUNT: Snowflake (dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS)
SELECT COUNT(*) AS target_row_count
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE;

-- ──────────────────────────────────────────────────────────────────────
-- ③ MAIN VALIDATION — PostgreSQL (normalised data — export CSV, compare with ④)
-- ──────────────────────────────────────────────────────────────────────
-- ③ SOURCE: PostgreSQL (public.general_ledger_line_items)
SELECT
    COALESCE(CAST(TO_CHAR(effective_on, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS effective_on_normalized,
    COALESCE(CAST(TRIM(description) AS TEXT), '<<NULL>>') AS description_normalized,
    COALESCE(CAST(ROUND(CAST(amount AS NUMERIC), 2) AS TEXT), '<<NULL>>') AS amount_normalized,
    COALESCE(CAST(CAST(account_balance_id AS TEXT) AS TEXT), '<<NULL>>') AS account_balance_id_normalized,
    COALESCE(CAST(CAST(tenant_id AS TEXT) AS TEXT), '<<NULL>>') AS tenant_id_normalized,
    COALESCE(CAST(CAST(ledger_id AS TEXT) AS TEXT), '<<NULL>>') AS ledger_id_normalized,
    COALESCE(CAST(CAST(facility_id AS TEXT) AS TEXT), '<<NULL>>') AS facility_id_normalized,
    COALESCE(CAST(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS created_at_normalized,
    COALESCE(CAST(TO_CHAR(updated_at, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS updated_at_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(uuid AS TEXT))) AS TEXT), '<<NULL>>') AS uuid_normalized,
    COALESCE(CAST(CASE WHEN reversal = true  THEN '1' WHEN reversal = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS reversal_normalized,
    COALESCE(CAST(CAST(account_balance_item_id AS TEXT) AS TEXT), '<<NULL>>') AS account_balance_item_id_normalized,
    COALESCE(CAST(TRIM(internal_account_code) AS TEXT), '<<NULL>>') AS internal_account_code_normalized,
    COALESCE(CAST(CASE WHEN daily_transaction = true  THEN '1' WHEN daily_transaction = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS daily_transaction_normalized,
    COALESCE(CAST(TRIM(transaction_type) AS TEXT), '<<NULL>>') AS transaction_type_normalized,
    COALESCE(CAST(CASE WHEN hidden = true  THEN '1' WHEN hidden = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS hidden_normalized,
    COALESCE(CAST(TRIM(reference_number) AS TEXT), '<<NULL>>') AS reference_number_normalized,
    COALESCE(CAST(TRIM(display_code) AS TEXT), '<<NULL>>') AS display_code_normalized,
    COALESCE(CAST(CAST(id AS TEXT) AS TEXT), '<<NULL>>') AS id_normalized
FROM public.general_ledger_line_items;

-- ──────────────────────────────────────────────────────────────────────
-- ④ MAIN VALIDATION — Snowflake  (normalised data — export CSV, compare with ③)
-- ──────────────────────────────────────────────────────────────────────
-- ④ TARGET: Snowflake (dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS)
SELECT
    COALESCE(CAST(TO_VARCHAR(EFFECTIVE_ON, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS effective_on_normalized,
    COALESCE(CAST(TRIM(DESCRIPTION) AS STRING), '<<NULL>>') AS description_normalized,
    COALESCE(CAST(ROUND(CAST(AMOUNT AS NUMBER(38, 2)), 2) AS STRING), '<<NULL>>') AS amount_normalized,
    COALESCE(CAST(CAST(ACCOUNT_BALANCE_ID AS STRING) AS STRING), '<<NULL>>') AS account_balance_id_normalized,
    COALESCE(CAST(CAST(TENANT_ID AS STRING) AS STRING), '<<NULL>>') AS tenant_id_normalized,
    COALESCE(CAST(CAST(LEDGER_ID AS STRING) AS STRING), '<<NULL>>') AS ledger_id_normalized,
    COALESCE(CAST(CAST(FACILITY_ID AS STRING) AS STRING), '<<NULL>>') AS facility_id_normalized,
    COALESCE(CAST(TO_VARCHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS created_at_normalized,
    COALESCE(CAST(TO_VARCHAR(UPDATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS updated_at_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(UUID AS STRING))) AS STRING), '<<NULL>>') AS uuid_normalized,
    COALESCE(CAST(CASE WHEN REVERSAL = TRUE  THEN '1' WHEN REVERSAL = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS reversal_normalized,
    COALESCE(CAST(CAST(ACCOUNT_BALANCE_ITEM_ID AS STRING) AS STRING), '<<NULL>>') AS account_balance_item_id_normalized,
    COALESCE(CAST(TRIM(INTERNAL_ACCOUNT_CODE) AS STRING), '<<NULL>>') AS internal_account_code_normalized,
    COALESCE(CAST(CASE WHEN DAILY_TRANSACTION = TRUE  THEN '1' WHEN DAILY_TRANSACTION = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS daily_transaction_normalized,
    COALESCE(CAST(TRIM(TRANSACTION_TYPE) AS STRING), '<<NULL>>') AS transaction_type_normalized,
    COALESCE(CAST(CASE WHEN HIDDEN = TRUE  THEN '1' WHEN HIDDEN = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS hidden_normalized,
    COALESCE(CAST(TRIM(REFERENCE_NUMBER) AS STRING), '<<NULL>>') AS reference_number_normalized,
    COALESCE(CAST(TRIM(DISPLAY_CODE) AS STRING), '<<NULL>>') AS display_code_normalized,
    COALESCE(CAST(CAST(ID AS STRING) AS STRING), '<<NULL>>') AS id_normalized
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE;

-- ──────────────────────────────────────────────────────────────────────
-- ⑤ NULL % PER COLUMN — PostgreSQL (compare null_pct values with ⑥)
-- ──────────────────────────────────────────────────────────────────────
-- ⑤ NULL % CHECK: PostgreSQL (public.general_ledger_line_items)
SELECT
    COUNT(*) AS total_rows,
    ROUND(100.0 * SUM(CASE WHEN effective_on IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS effective_on_null_pct,
    ROUND(100.0 * SUM(CASE WHEN description IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS description_null_pct,
    ROUND(100.0 * SUM(CASE WHEN amount IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS amount_null_pct,
    ROUND(100.0 * SUM(CASE WHEN account_balance_id IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS account_balance_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN tenant_id IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS tenant_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN ledger_id IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS ledger_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN facility_id IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS facility_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN created_at IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS created_at_null_pct,
    ROUND(100.0 * SUM(CASE WHEN updated_at IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS updated_at_null_pct,
    ROUND(100.0 * SUM(CASE WHEN uuid IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS uuid_null_pct,
    ROUND(100.0 * SUM(CASE WHEN reversal IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS reversal_null_pct,
    ROUND(100.0 * SUM(CASE WHEN account_balance_item_id IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS account_balance_item_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN internal_account_code IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS internal_account_code_null_pct,
    ROUND(100.0 * SUM(CASE WHEN daily_transaction IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS daily_transaction_null_pct,
    ROUND(100.0 * SUM(CASE WHEN transaction_type IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS transaction_type_null_pct,
    ROUND(100.0 * SUM(CASE WHEN hidden IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS hidden_null_pct,
    ROUND(100.0 * SUM(CASE WHEN reference_number IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS reference_number_null_pct,
    ROUND(100.0 * SUM(CASE WHEN display_code IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS display_code_null_pct,
    ROUND(100.0 * SUM(CASE WHEN id IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS id_null_pct
FROM public.general_ledger_line_items;

-- ──────────────────────────────────────────────────────────────────────
-- ⑥ NULL % PER COLUMN — Snowflake  (compare null_pct values with ⑤)
-- ──────────────────────────────────────────────────────────────────────
-- ⑥ NULL % CHECK: Snowflake (dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS)
SELECT
    COUNT(*) AS total_rows,
    ROUND(100.0 * SUM(CASE WHEN EFFECTIVE_ON IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS effective_on_null_pct,
    ROUND(100.0 * SUM(CASE WHEN DESCRIPTION IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS description_null_pct,
    ROUND(100.0 * SUM(CASE WHEN AMOUNT IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS amount_null_pct,
    ROUND(100.0 * SUM(CASE WHEN ACCOUNT_BALANCE_ID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS account_balance_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN TENANT_ID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS tenant_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN LEDGER_ID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS ledger_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN FACILITY_ID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS facility_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN CREATED_AT IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS created_at_null_pct,
    ROUND(100.0 * SUM(CASE WHEN UPDATED_AT IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS updated_at_null_pct,
    ROUND(100.0 * SUM(CASE WHEN UUID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS uuid_null_pct,
    ROUND(100.0 * SUM(CASE WHEN REVERSAL IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS reversal_null_pct,
    ROUND(100.0 * SUM(CASE WHEN ACCOUNT_BALANCE_ITEM_ID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS account_balance_item_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN INTERNAL_ACCOUNT_CODE IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS internal_account_code_null_pct,
    ROUND(100.0 * SUM(CASE WHEN DAILY_TRANSACTION IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS daily_transaction_null_pct,
    ROUND(100.0 * SUM(CASE WHEN TRANSACTION_TYPE IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS transaction_type_null_pct,
    ROUND(100.0 * SUM(CASE WHEN HIDDEN IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS hidden_null_pct,
    ROUND(100.0 * SUM(CASE WHEN REFERENCE_NUMBER IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS reference_number_null_pct,
    ROUND(100.0 * SUM(CASE WHEN DISPLAY_CODE IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS display_code_null_pct,
    ROUND(100.0 * SUM(CASE WHEN ID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS id_null_pct
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE;

-- ──────────────────────────────────────────────────────────────────────
-- ⑦ DISTINCT VALUE COUNT — PostgreSQL (compare distinct_count with ⑧)
-- ──────────────────────────────────────────────────────────────────────
-- ⑦ DISTINCT VALUE COUNT: PostgreSQL (public.general_ledger_line_items)
-- Compare distinct counts with ⑧ — large differences indicate data drift.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT effective_on) AS effective_on_distinct_count,
    COUNT(DISTINCT description) AS description_distinct_count,
    COUNT(DISTINCT amount) AS amount_distinct_count,
    COUNT(DISTINCT account_balance_id) AS account_balance_id_distinct_count,
    COUNT(DISTINCT tenant_id) AS tenant_id_distinct_count,
    COUNT(DISTINCT ledger_id) AS ledger_id_distinct_count,
    COUNT(DISTINCT facility_id) AS facility_id_distinct_count,
    COUNT(DISTINCT created_at) AS created_at_distinct_count,
    COUNT(DISTINCT updated_at) AS updated_at_distinct_count,
    COUNT(DISTINCT uuid) AS uuid_distinct_count,
    COUNT(DISTINCT reversal) AS reversal_distinct_count,
    COUNT(DISTINCT account_balance_item_id) AS account_balance_item_id_distinct_count,
    COUNT(DISTINCT internal_account_code) AS internal_account_code_distinct_count,
    COUNT(DISTINCT daily_transaction) AS daily_transaction_distinct_count,
    COUNT(DISTINCT transaction_type) AS transaction_type_distinct_count,
    COUNT(DISTINCT hidden) AS hidden_distinct_count,
    COUNT(DISTINCT reference_number) AS reference_number_distinct_count,
    COUNT(DISTINCT display_code) AS display_code_distinct_count,
    COUNT(DISTINCT id) AS id_distinct_count
FROM public.general_ledger_line_items;

-- ──────────────────────────────────────────────────────────────────────
-- ⑧ DISTINCT VALUE COUNT — Snowflake  (compare distinct_count with ⑦)
-- ──────────────────────────────────────────────────────────────────────
-- ⑧ DISTINCT VALUE COUNT: Snowflake (dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS)
-- Compare distinct counts with ⑦ — large differences indicate data drift.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT EFFECTIVE_ON) AS effective_on_distinct_count,
    COUNT(DISTINCT DESCRIPTION) AS description_distinct_count,
    COUNT(DISTINCT AMOUNT) AS amount_distinct_count,
    COUNT(DISTINCT ACCOUNT_BALANCE_ID) AS account_balance_id_distinct_count,
    COUNT(DISTINCT TENANT_ID) AS tenant_id_distinct_count,
    COUNT(DISTINCT LEDGER_ID) AS ledger_id_distinct_count,
    COUNT(DISTINCT FACILITY_ID) AS facility_id_distinct_count,
    COUNT(DISTINCT CREATED_AT) AS created_at_distinct_count,
    COUNT(DISTINCT UPDATED_AT) AS updated_at_distinct_count,
    COUNT(DISTINCT UUID) AS uuid_distinct_count,
    COUNT(DISTINCT REVERSAL) AS reversal_distinct_count,
    COUNT(DISTINCT ACCOUNT_BALANCE_ITEM_ID) AS account_balance_item_id_distinct_count,
    COUNT(DISTINCT INTERNAL_ACCOUNT_CODE) AS internal_account_code_distinct_count,
    COUNT(DISTINCT DAILY_TRANSACTION) AS daily_transaction_distinct_count,
    COUNT(DISTINCT TRANSACTION_TYPE) AS transaction_type_distinct_count,
    COUNT(DISTINCT HIDDEN) AS hidden_distinct_count,
    COUNT(DISTINCT REFERENCE_NUMBER) AS reference_number_distinct_count,
    COUNT(DISTINCT DISPLAY_CODE) AS display_code_distinct_count,
    COUNT(DISTINCT ID) AS id_distinct_count
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE;
