-- ========================================================================
-- DYNAMIC MIGRATION VALIDATOR — Generated Validation Suite
-- Source       : public.general_ledger_line_items
-- Target       : dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
-- Generated    : 2026-08-10T20:04:24.452039
-- Generated by : AI
-- AI Model     : gpt-4o
-- Total checks : 4 query pair(s)
-- Fivetran     : YES — WHERE _FIVETRAN_ACTIVE = TRUE
-- ========================================================================

-- HOW TO USE:
-- 1. Run each SOURCE query on PostgreSQL, each TARGET on Snowflake.
-- 2. Compare the result sets as instructed in the comparison note.
-- 3. Any row-count difference OR value mismatch = FAIL.
-- 4. Aggregate queries (MIN/MAX/SUM) are combined — compare columns.
-- ========================================================================

-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ① ROW COUNT: PostgreSQL (public.general_ledger_line_items)
SELECT COUNT(*) AS source_row_count
FROM public.general_ledger_line_items;
-- Compare: source_row_count must equal target_row_count

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ② ROW COUNT: Snowflake (dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS)
SELECT COUNT(*) AS target_row_count
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ③ SOURCE: PostgreSQL (public.general_ledger_line_items)
SELECT
    COALESCE(CAST(TO_CHAR(effective_on, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS effective_on_normalized,
    COALESCE(CAST(TRIM(description) AS TEXT), '<<NULL>>') AS description_normalized,
    COALESCE(CAST(ROUND(CAST(amount AS NUMERIC), 2) AS TEXT), '<<NULL>>') AS amount_normalized,
    COALESCE(CAST(CAST(account_balance_id AS TEXT) AS TEXT), '<<NULL>>') AS account_balance_id_normalized,
    COALESCE(CAST(CAST(tenant_id AS TEXT) AS TEXT), '<<NULL>>') AS tenant_id_normalized,
    COALESCE(CAST(CAST(ledger_id AS TEXT) AS TEXT), '<<NULL>>') AS ledger_id_normalized,
    COALESCE(CAST(CAST(facility_id AS TEXT) AS TEXT), '<<NULL>>') AS facility_id_normalized,
    COALESCE(CAST(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS created_at_normalized,
    COALESCE(CAST(TO_CHAR(updated_at, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS updated_at_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(uuid AS TEXT))) AS TEXT), '<<NULL>>') AS uuid_normalized,
    COALESCE(CAST(CASE WHEN reversal = true  THEN '1' WHEN reversal = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS reversal_normalized,
    COALESCE(CAST(CAST(account_balance_item_id AS TEXT) AS TEXT), '<<NULL>>') AS account_balance_item_id_normalized,
    COALESCE(CAST(TRIM(internal_account_code) AS TEXT), '<<NULL>>') AS internal_account_code_normalized,
    COALESCE(CAST(CASE WHEN daily_transaction = true  THEN '1' WHEN daily_transaction = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS daily_transaction_normalized,
    COALESCE(CAST(TRIM(transaction_type) AS TEXT), '<<NULL>>') AS transaction_type_normalized,
    COALESCE(CAST(CASE WHEN hidden = true  THEN '1' WHEN hidden = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS hidden_normalized,
    COALESCE(CAST(TRIM(reference_number) AS TEXT), '<<NULL>>') AS reference_number_normalized,
    COALESCE(CAST(TRIM(display_code) AS TEXT), '<<NULL>>') AS display_code_normalized,
    COALESCE(CAST(CAST(id AS TEXT) AS TEXT), '<<NULL>>') AS id_normalized
FROM public.general_ledger_line_items;
-- Compare: Export both to CSV. Compare row-by-row — must be identical. All values are normalised so comparison is type-safe.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ④ TARGET: Snowflake (dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS)
SELECT
    COALESCE(CAST(TO_VARCHAR(EFFECTIVE_ON, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS effective_on_normalized,
    COALESCE(CAST(TRIM(DESCRIPTION) AS STRING), '<<NULL>>') AS description_normalized,
    COALESCE(CAST(ROUND(CAST(AMOUNT AS NUMBER(38, 2)), 2) AS STRING), '<<NULL>>') AS amount_normalized,
    COALESCE(CAST(CAST(ACCOUNT_BALANCE_ID AS STRING) AS STRING), '<<NULL>>') AS account_balance_id_normalized,
    COALESCE(CAST(CAST(TENANT_ID AS STRING) AS STRING), '<<NULL>>') AS tenant_id_normalized,
    COALESCE(CAST(CAST(LEDGER_ID AS STRING) AS STRING), '<<NULL>>') AS ledger_id_normalized,
    COALESCE(CAST(CAST(FACILITY_ID AS STRING) AS STRING), '<<NULL>>') AS facility_id_normalized,
    COALESCE(CAST(TO_VARCHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS created_at_normalized,
    COALESCE(CAST(TO_VARCHAR(UPDATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS updated_at_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(UUID AS STRING))) AS STRING), '<<NULL>>') AS uuid_normalized,
    COALESCE(CAST(CASE WHEN REVERSAL = TRUE  THEN '1' WHEN REVERSAL = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS reversal_normalized,
    COALESCE(CAST(CAST(ACCOUNT_BALANCE_ITEM_ID AS STRING) AS STRING), '<<NULL>>') AS account_balance_item_id_normalized,
    COALESCE(CAST(TRIM(INTERNAL_ACCOUNT_CODE) AS STRING), '<<NULL>>') AS internal_account_code_normalized,
    COALESCE(CAST(CASE WHEN DAILY_TRANSACTION = TRUE  THEN '1' WHEN DAILY_TRANSACTION = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS daily_transaction_normalized,
    COALESCE(CAST(TRIM(TRANSACTION_TYPE) AS STRING), '<<NULL>>') AS transaction_type_normalized,
    COALESCE(CAST(CASE WHEN HIDDEN = TRUE  THEN '1' WHEN HIDDEN = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS hidden_normalized,
    COALESCE(CAST(TRIM(REFERENCE_NUMBER) AS STRING), '<<NULL>>') AS reference_number_normalized,
    COALESCE(CAST(TRIM(DISPLAY_CODE) AS STRING), '<<NULL>>') AS display_code_normalized,
    COALESCE(CAST(CAST(ID AS STRING) AS STRING), '<<NULL>>') AS id_normalized
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + MIN/MAX + SUM + VALUE_DIST)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: PostgreSQL (public.general_ledger_line_items)
-- Includes: NULL% + DISTINCT + MIN/MAX + SUM + VALUE_DIST
-- One scan replaces 5 separate aggregate query types.
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN effective_on IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS effective_on_null_pct
    ROUND(100.0 * SUM(CASE WHEN description IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS description_null_pct
    ROUND(100.0 * SUM(CASE WHEN amount IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS amount_null_pct
    ROUND(100.0 * SUM(CASE WHEN account_balance_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS account_balance_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN tenant_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS tenant_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN ledger_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS ledger_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN facility_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS facility_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN created_at IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS created_at_null_pct
    ROUND(100.0 * SUM(CASE WHEN updated_at IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS updated_at_null_pct
    ROUND(100.0 * SUM(CASE WHEN uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN reversal IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS reversal_null_pct
    ROUND(100.0 * SUM(CASE WHEN account_balance_item_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS account_balance_item_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN internal_account_code IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS internal_account_code_null_pct
    ROUND(100.0 * SUM(CASE WHEN daily_transaction IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS daily_transaction_null_pct
    ROUND(100.0 * SUM(CASE WHEN transaction_type IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS transaction_type_null_pct
    ROUND(100.0 * SUM(CASE WHEN hidden IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS hidden_null_pct
    ROUND(100.0 * SUM(CASE WHEN reference_number IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS reference_number_null_pct
    ROUND(100.0 * SUM(CASE WHEN display_code IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS display_code_null_pct
    ROUND(100.0 * SUM(CASE WHEN id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS id_null_pct
    COUNT(DISTINCT effective_on) AS effective_on_distinct_count
    COUNT(DISTINCT description) AS description_distinct_count
    COUNT(DISTINCT amount) AS amount_distinct_count
    COUNT(DISTINCT account_balance_id) AS account_balance_id_distinct_count
    COUNT(DISTINCT tenant_id) AS tenant_id_distinct_count
    COUNT(DISTINCT ledger_id) AS ledger_id_distinct_count
    COUNT(DISTINCT facility_id) AS facility_id_distinct_count
    COUNT(DISTINCT created_at) AS created_at_distinct_count
    COUNT(DISTINCT updated_at) AS updated_at_distinct_count
    COUNT(DISTINCT uuid) AS uuid_distinct_count
    COUNT(DISTINCT reversal) AS reversal_distinct_count
    COUNT(DISTINCT account_balance_item_id) AS account_balance_item_id_distinct_count
    COUNT(DISTINCT internal_account_code) AS internal_account_code_distinct_count
    COUNT(DISTINCT daily_transaction) AS daily_transaction_distinct_count
    COUNT(DISTINCT transaction_type) AS transaction_type_distinct_count
    COUNT(DISTINCT hidden) AS hidden_distinct_count
    COUNT(DISTINCT reference_number) AS reference_number_distinct_count
    COUNT(DISTINCT display_code) AS display_code_distinct_count
    COUNT(DISTINCT id) AS id_distinct_count
    MIN(amount) AS amount_min
    MAX(amount) AS amount_max
    SUM(amount) AS amount_sum
FROM public.general_ledger_line_items;
-- Compare: Compare each _null_pct, _distinct_count, _min, _max, _sum column between source and target. Column names are identical so direct comparison is possible.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + MIN/MAX + SUM + VALUE_DIST)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: Snowflake (dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS)
-- Includes: NULL% + DISTINCT + MIN/MAX + SUM + VALUE_DIST
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN EFFECTIVE_ON IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS effective_on_null_pct
    ROUND(100.0 * SUM(CASE WHEN DESCRIPTION IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS description_null_pct
    ROUND(100.0 * SUM(CASE WHEN AMOUNT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS amount_null_pct
    ROUND(100.0 * SUM(CASE WHEN ACCOUNT_BALANCE_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS account_balance_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN TENANT_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS tenant_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN LEDGER_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS ledger_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN FACILITY_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS facility_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN CREATED_AT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS created_at_null_pct
    ROUND(100.0 * SUM(CASE WHEN UPDATED_AT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS updated_at_null_pct
    ROUND(100.0 * SUM(CASE WHEN UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN REVERSAL IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS reversal_null_pct
    ROUND(100.0 * SUM(CASE WHEN ACCOUNT_BALANCE_ITEM_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS account_balance_item_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN INTERNAL_ACCOUNT_CODE IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS internal_account_code_null_pct
    ROUND(100.0 * SUM(CASE WHEN DAILY_TRANSACTION IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS daily_transaction_null_pct
    ROUND(100.0 * SUM(CASE WHEN TRANSACTION_TYPE IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS transaction_type_null_pct
    ROUND(100.0 * SUM(CASE WHEN HIDDEN IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS hidden_null_pct
    ROUND(100.0 * SUM(CASE WHEN REFERENCE_NUMBER IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS reference_number_null_pct
    ROUND(100.0 * SUM(CASE WHEN DISPLAY_CODE IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS display_code_null_pct
    ROUND(100.0 * SUM(CASE WHEN ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS id_null_pct
    COUNT(DISTINCT EFFECTIVE_ON) AS effective_on_distinct_count
    COUNT(DISTINCT DESCRIPTION) AS description_distinct_count
    COUNT(DISTINCT AMOUNT) AS amount_distinct_count
    COUNT(DISTINCT ACCOUNT_BALANCE_ID) AS account_balance_id_distinct_count
    COUNT(DISTINCT TENANT_ID) AS tenant_id_distinct_count
    COUNT(DISTINCT LEDGER_ID) AS ledger_id_distinct_count
    COUNT(DISTINCT FACILITY_ID) AS facility_id_distinct_count
    COUNT(DISTINCT CREATED_AT) AS created_at_distinct_count
    COUNT(DISTINCT UPDATED_AT) AS updated_at_distinct_count
    COUNT(DISTINCT UUID) AS uuid_distinct_count
    COUNT(DISTINCT REVERSAL) AS reversal_distinct_count
    COUNT(DISTINCT ACCOUNT_BALANCE_ITEM_ID) AS account_balance_item_id_distinct_count
    COUNT(DISTINCT INTERNAL_ACCOUNT_CODE) AS internal_account_code_distinct_count
    COUNT(DISTINCT DAILY_TRANSACTION) AS daily_transaction_distinct_count
    COUNT(DISTINCT TRANSACTION_TYPE) AS transaction_type_distinct_count
    COUNT(DISTINCT HIDDEN) AS hidden_distinct_count
    COUNT(DISTINCT REFERENCE_NUMBER) AS reference_number_distinct_count
    COUNT(DISTINCT DISPLAY_CODE) AS display_code_distinct_count
    COUNT(DISTINCT ID) AS id_distinct_count
    MIN(AMOUNT) AS amount_min
    MAX(AMOUNT) AS amount_max
    SUM(AMOUNT) AS amount_sum
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ⑬ / ⑭ — Duplicate Check (Business Key)
-- ────────────────────────────────────────────────────────────────────────
-- ⑬ DUPLICATE CHECK: PostgreSQL (public.general_ledger_line_items)
-- Expect: 0 rows returned. Any row = duplicate business key.
SELECT
    id,
    COUNT(*) AS duplicate_count
FROM public.general_ledger_line_items
GROUP BY id
HAVING COUNT(*) > 1;
-- Compare: Both queries should return 0 rows. Any row means duplicate business-key values exist.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ⑬ / ⑭ — Duplicate Check (Business Key)
-- ────────────────────────────────────────────────────────────────────────
-- ⑭ DUPLICATE CHECK: Snowflake (dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS)
-- Expect: 0 rows returned. Any row = duplicate business key.
SELECT
    ID,
    COUNT(*) AS duplicate_count
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE
GROUP BY ID
HAVING COUNT(*) > 1;


-- ========================================================================
-- AI-RECOMMENDED BUSINESS RULE CHECKS
-- These are condition fragments. Run as:
--   SELECT COUNT(*) FROM <table> WHERE NOT (<condition>);
-- Any count > 0 = data quality issue.
-- ========================================================================

-- AI Recommendation: Ensure that the financial amount is non-negative.
-- Severity : error
-- Columns  : amount
-- Condition: amount >= 0
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.general_ledger_line_items
WHERE NOT (amount >= 0);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (amount >= 0);


-- AI Recommendation: Ensure that the created_at timestamp is earlier than or equal to the updated_at timestamp.
-- Severity : error
-- Columns  : created_at, updated_at
-- Condition: created_at <= updated_at
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.general_ledger_line_items
WHERE NOT (created_at <= updated_at);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (created_at <= updated_at);


-- AI Recommendation: Ensure that the UUID column is not null.
-- Severity : error
-- Columns  : uuid
-- Condition: uuid IS NOT NULL
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.general_ledger_line_items
WHERE NOT (uuid IS NOT NULL);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (uuid IS NOT NULL);


-- AI Recommendation: Ensure that the transaction_type column is not empty or null.
-- Severity : warning
-- Columns  : transaction_type
-- Condition: transaction_type IS NOT NULL AND transaction_type <> ''
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.general_ledger_line_items
WHERE NOT (transaction_type IS NOT NULL AND transaction_type <> '');

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (transaction_type IS NOT NULL AND transaction_type <> '');


-- AI Recommendation: Ensure that the primary key ID is a positive value.
-- Severity : error
-- Columns  : id
-- Condition: id > 0
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.general_ledger_line_items
WHERE NOT (id > 0);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM dev_edge_bronze.storedge_fms_public.GENERAL_LEDGER_LINE_ITEMS
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (id > 0);

