-- ========================================================================
-- DYNAMIC MIGRATION VALIDATOR — Generated Validation Suite
-- Source       : public.migration_test
-- Target       : DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
-- Generated    : 2026-08-12T17:51:29.131085
-- Generated by : AI
-- AI Model     : gpt-4o
-- Total checks : 4 query pair(s)
-- Fivetran     : YES — WHERE _FIVETRAN_ACTIVE = TRUE
-- ========================================================================

-- HOW TO USE:
-- 1. Run each SOURCE query on PostgreSQL, each TARGET on Snowflake.
-- 2. Compare the result sets as instructed in the comparison note.
-- 3. Any row-count difference OR value mismatch = FAIL.
-- 4. Aggregate queries (MIN/MAX/SUM) are combined — compare columns.
-- ========================================================================

-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ① ROW COUNT: PostgreSQL (public.migration_test)
SELECT COUNT(*) AS source_row_count
FROM public.migration_test;
-- Compare: source_row_count must equal target_row_count

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ① / ② — Row Count
-- ────────────────────────────────────────────────────────────────────────
-- ② ROW COUNT: Snowflake (DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST)
SELECT COUNT(*) AS target_row_count
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ③ SOURCE: PostgreSQL (public.migration_test)
SELECT
    COALESCE(CAST(CAST(row_id AS TEXT) AS TEXT), '<<NULL>>') AS row_id_normalized,
    COALESCE(CAST(TRIM(col_varchar) AS TEXT), '<<NULL>>') AS col_varchar_normalized,
    COALESCE(CAST(TRIM(col_text) AS TEXT), '<<NULL>>') AS col_text_normalized,
    COALESCE(CAST(TRIM(col_char) AS TEXT), '<<NULL>>') AS col_char_normalized,
    COALESCE(CAST(CASE WHEN col_boolean = true THEN '1' WHEN col_boolean = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS col_boolean_normalized,
    COALESCE(CAST(CAST(col_smallint AS TEXT) AS TEXT), '<<NULL>>') AS col_smallint_normalized,
    COALESCE(CAST(CAST(col_integer AS TEXT) AS TEXT), '<<NULL>>') AS col_integer_normalized,
    COALESCE(CAST(CAST(col_bigint AS TEXT) AS TEXT), '<<NULL>>') AS col_bigint_normalized,
    COALESCE(CAST(ROUND(CAST(col_numeric AS NUMERIC), 2) AS TEXT), '<<NULL>>') AS col_numeric_normalized,
    COALESCE(CAST(ROUND(CAST(col_decimal AS NUMERIC), 2) AS TEXT), '<<NULL>>') AS col_decimal_normalized,
    COALESCE(CAST(ROUND(CAST(col_float AS NUMERIC), 2) AS TEXT), '<<NULL>>') AS col_float_normalized,
    COALESCE(CAST(TO_CHAR(col_date, 'YYYY-MM-DD') AS TEXT), '<<NULL>>') AS col_date_normalized,
    COALESCE(CAST(TO_CHAR(col_timestamp_ntz, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS col_timestamp_ntz_normalized,
    COALESCE(CAST(TO_CHAR(col_timestamp_tz AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS col_timestamp_tz_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(col_uuid AS TEXT))) AS TEXT), '<<NULL>>') AS col_uuid_normalized,
    COALESCE(CAST(col_json::jsonb::text AS TEXT), '<<NULL>>') AS col_json_normalized,
    COALESCE(CAST(col_jsonb::jsonb::text AS TEXT), '<<NULL>>') AS col_jsonb_normalized,
    COALESCE(CAST(encode(col_bytea, 'hex') AS TEXT), '<<NULL>>') AS col_bytea_normalized,
    COALESCE(CAST(TRIM(CAST(col_hstore AS TEXT)) AS TEXT), '<<NULL>>') AS col_hstore_normalized,
    COALESCE(CAST(TRIM(test_label) AS TEXT), '<<NULL>>') AS test_label_normalized
FROM public.migration_test;
-- Compare: Export both to CSV. Compare row-by-row — must be identical. All values are normalised so comparison is type-safe.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ③ / ④ — Full Data Validation (normalised)
-- ────────────────────────────────────────────────────────────────────────
-- ④ TARGET: Snowflake (DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST)
SELECT
    COALESCE(CAST(CAST(ROW_ID AS STRING) AS STRING), '<<NULL>>') AS row_id_normalized,
    COALESCE(CAST(TRIM(COL_VARCHAR) AS STRING), '<<NULL>>') AS col_varchar_normalized,
    COALESCE(CAST(TRIM(COL_TEXT) AS STRING), '<<NULL>>') AS col_text_normalized,
    COALESCE(CAST(TRIM(COL_CHAR) AS STRING), '<<NULL>>') AS col_char_normalized,
    COALESCE(CAST(CASE WHEN COL_BOOLEAN = TRUE THEN '1' WHEN COL_BOOLEAN = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS col_boolean_normalized,
    COALESCE(CAST(CAST(COL_SMALLINT AS STRING) AS STRING), '<<NULL>>') AS col_smallint_normalized,
    COALESCE(CAST(CAST(COL_INTEGER AS STRING) AS STRING), '<<NULL>>') AS col_integer_normalized,
    COALESCE(CAST(CAST(COL_BIGINT AS STRING) AS STRING), '<<NULL>>') AS col_bigint_normalized,
    COALESCE(CAST(ROUND(CAST(COL_NUMERIC AS NUMBER(38, 2)), 2) AS STRING), '<<NULL>>') AS col_numeric_normalized,
    COALESCE(CAST(ROUND(CAST(COL_DECIMAL AS NUMBER(38, 2)), 2) AS STRING), '<<NULL>>') AS col_decimal_normalized,
    COALESCE(CAST(ROUND(CAST(COL_FLOAT AS NUMBER(38, 2)), 2) AS STRING), '<<NULL>>') AS col_float_normalized,
    COALESCE(CAST(TO_VARCHAR(COL_DATE, 'YYYY-MM-DD') AS STRING), '<<NULL>>') AS col_date_normalized,
    COALESCE(CAST(TO_VARCHAR(COL_TIMESTAMP_NTZ, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS col_timestamp_ntz_normalized,
    COALESCE(CAST(TO_VARCHAR(CONVERT_TIMEZONE('UTC', COL_TIMESTAMP_TZ), 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS col_timestamp_tz_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(COL_UUID AS STRING))) AS STRING), '<<NULL>>') AS col_uuid_normalized,
    COALESCE(CAST(TO_JSON(PARSE_JSON(CAST(COL_JSON AS STRING))) AS STRING), '<<NULL>>') AS col_json_normalized,
    COALESCE(CAST(TO_JSON(PARSE_JSON(CAST(COL_JSONB AS STRING))) AS STRING), '<<NULL>>') AS col_jsonb_normalized,
    COALESCE(CAST(LOWER(HEX_ENCODE(COL_BYTEA)) AS STRING), '<<NULL>>') AS col_bytea_normalized,
    COALESCE(CAST(TRIM(COL_HSTORE) AS STRING), '<<NULL>>') AS col_hstore_normalized,
    COALESCE(CAST(TRIM(TEST_LABEL) AS STRING), '<<NULL>>') AS test_label_normalized
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + MIN/MAX + VALUE_DIST)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: PostgreSQL (public.migration_test)
-- Includes: NULL% + DISTINCT + MIN/MAX + VALUE_DIST
-- One scan replaces 4 separate aggregate query types.
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN row_id IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS row_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_varchar IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_varchar_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_text IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_text_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_char IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_char_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_boolean IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_boolean_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_smallint IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_smallint_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_integer IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_integer_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_bigint IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_bigint_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_numeric IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_numeric_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_decimal IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_decimal_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_float IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_float_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_date IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_date_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_timestamp_ntz IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_timestamp_ntz_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_timestamp_tz IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_timestamp_tz_null_pct
    ROUND(100.0 * SUM(CASE WHEN col_uuid IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN test_label IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS test_label_null_pct
    COUNT(DISTINCT row_id) AS row_id_distinct_count
    COUNT(DISTINCT col_varchar) AS col_varchar_distinct_count
    COUNT(DISTINCT col_text) AS col_text_distinct_count
    COUNT(DISTINCT col_char) AS col_char_distinct_count
    COUNT(DISTINCT col_boolean) AS col_boolean_distinct_count
    COUNT(DISTINCT col_smallint) AS col_smallint_distinct_count
    COUNT(DISTINCT col_integer) AS col_integer_distinct_count
    COUNT(DISTINCT col_bigint) AS col_bigint_distinct_count
    COUNT(DISTINCT col_numeric) AS col_numeric_distinct_count
    COUNT(DISTINCT col_decimal) AS col_decimal_distinct_count
    COUNT(DISTINCT col_float) AS col_float_distinct_count
    COUNT(DISTINCT col_date) AS col_date_distinct_count
    COUNT(DISTINCT col_timestamp_ntz) AS col_timestamp_ntz_distinct_count
    COUNT(DISTINCT col_timestamp_tz) AS col_timestamp_tz_distinct_count
    COUNT(DISTINCT col_uuid) AS col_uuid_distinct_count
    COUNT(DISTINCT test_label) AS test_label_distinct_count
    MIN(col_smallint) AS col_smallint_min
    MAX(col_smallint) AS col_smallint_max
    MIN(col_integer) AS col_integer_min
    MAX(col_integer) AS col_integer_max
    MIN(col_bigint) AS col_bigint_min
    MAX(col_bigint) AS col_bigint_max
    MIN(col_numeric) AS col_numeric_min
    MAX(col_numeric) AS col_numeric_max
    MIN(col_decimal) AS col_decimal_min
    MAX(col_decimal) AS col_decimal_max
    MIN(col_float) AS col_float_min
    MAX(col_float) AS col_float_max
FROM public.migration_test;
-- Compare: Compare each _null_pct, _distinct_count, _min, _max, _sum column between source and target. Column names are identical so direct comparison is possible.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ⑤–⑫ combined — Combined Aggregate Query (NULL% + DISTINCT + MIN/MAX + VALUE_DIST)
-- ────────────────────────────────────────────────────────────────────────
-- ⑤–⑫ COMBINED AGGREGATE: Snowflake (DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST)
-- Includes: NULL% + DISTINCT + MIN/MAX + VALUE_DIST
SELECT
    COUNT(*) AS total_rows
    ROUND(100.0 * SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS row_id_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_VARCHAR IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_varchar_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_TEXT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_text_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_CHAR IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_char_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_BOOLEAN IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_boolean_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_SMALLINT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_smallint_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_INTEGER IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_integer_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_BIGINT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_bigint_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_NUMERIC IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_numeric_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_DECIMAL IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_decimal_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_FLOAT IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_float_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_DATE IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_date_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_TIMESTAMP_NTZ IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_timestamp_ntz_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_TIMESTAMP_TZ IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_timestamp_tz_null_pct
    ROUND(100.0 * SUM(CASE WHEN COL_UUID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS col_uuid_null_pct
    ROUND(100.0 * SUM(CASE WHEN TEST_LABEL IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS test_label_null_pct
    COUNT(DISTINCT ROW_ID) AS row_id_distinct_count
    COUNT(DISTINCT COL_VARCHAR) AS col_varchar_distinct_count
    COUNT(DISTINCT COL_TEXT) AS col_text_distinct_count
    COUNT(DISTINCT COL_CHAR) AS col_char_distinct_count
    COUNT(DISTINCT COL_BOOLEAN) AS col_boolean_distinct_count
    COUNT(DISTINCT COL_SMALLINT) AS col_smallint_distinct_count
    COUNT(DISTINCT COL_INTEGER) AS col_integer_distinct_count
    COUNT(DISTINCT COL_BIGINT) AS col_bigint_distinct_count
    COUNT(DISTINCT COL_NUMERIC) AS col_numeric_distinct_count
    COUNT(DISTINCT COL_DECIMAL) AS col_decimal_distinct_count
    COUNT(DISTINCT COL_FLOAT) AS col_float_distinct_count
    COUNT(DISTINCT COL_DATE) AS col_date_distinct_count
    COUNT(DISTINCT COL_TIMESTAMP_NTZ) AS col_timestamp_ntz_distinct_count
    COUNT(DISTINCT COL_TIMESTAMP_TZ) AS col_timestamp_tz_distinct_count
    COUNT(DISTINCT COL_UUID) AS col_uuid_distinct_count
    COUNT(DISTINCT TEST_LABEL) AS test_label_distinct_count
    MIN(COL_SMALLINT) AS col_smallint_min
    MAX(COL_SMALLINT) AS col_smallint_max
    MIN(COL_INTEGER) AS col_integer_min
    MAX(COL_INTEGER) AS col_integer_max
    MIN(COL_BIGINT) AS col_bigint_min
    MAX(COL_BIGINT) AS col_bigint_max
    MIN(COL_NUMERIC) AS col_numeric_min
    MAX(COL_NUMERIC) AS col_numeric_max
    MIN(COL_DECIMAL) AS col_decimal_min
    MAX(COL_DECIMAL) AS col_decimal_max
    MIN(COL_FLOAT) AS col_float_min
    MAX(COL_FLOAT) AS col_float_max
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST WHERE _FIVETRAN_ACTIVE = TRUE;


-- ────────────────────────────────────────────────────────────────────────
-- SOURCE ⑬ / ⑭ — Duplicate Check (Business Key)
-- ────────────────────────────────────────────────────────────────────────
-- ⑬ DUPLICATE CHECK: PostgreSQL (public.migration_test)
-- Expect: 0 rows returned. Any row = duplicate business key.
SELECT
    row_id,
    COUNT(*) AS duplicate_count
FROM public.migration_test
GROUP BY row_id
HAVING COUNT(*) > 1;
-- Compare: Both queries should return 0 rows. Any row means duplicate business-key values exist.

-- ────────────────────────────────────────────────────────────────────────
-- TARGET ⑬ / ⑭ — Duplicate Check (Business Key)
-- ────────────────────────────────────────────────────────────────────────
-- ⑭ DUPLICATE CHECK: Snowflake (DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST)
-- Expect: 0 rows returned. Any row = duplicate business key.
SELECT
    ROW_ID,
    COUNT(*) AS duplicate_count
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE
GROUP BY ROW_ID
HAVING COUNT(*) > 1;


-- ========================================================================
-- AI-RECOMMENDED BUSINESS RULE CHECKS
-- These are condition fragments. Run as:
--   SELECT COUNT(*) FROM <table> WHERE NOT (<condition>);
-- Any count > 0 = data quality issue.
-- ========================================================================

-- AI Recommendation: Ensure numeric columns do not contain negative values.
-- Severity : error
-- Columns  : col_smallint, col_integer, col_bigint, col_numeric, col_decimal, col_float
-- Condition: col_smallint < 0 OR col_integer < 0 OR col_bigint < 0 OR col_numeric < 0 OR col_decimal < 0 OR col_float < 0
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.migration_test
WHERE NOT (col_smallint < 0 OR col_integer < 0 OR col_bigint < 0 OR col_numeric < 0 OR col_decimal < 0 OR col_float < 0);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (col_smallint < 0 OR col_integer < 0 OR col_bigint < 0 OR col_numeric < 0 OR col_decimal < 0 OR col_float < 0);


-- AI Recommendation: Ensure boolean column does not contain NULL values if it is expected to represent a status flag.
-- Severity : warning
-- Columns  : col_boolean
-- Condition: col_boolean IS NULL
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.migration_test
WHERE NOT (col_boolean IS NULL);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (col_boolean IS NULL);


-- AI Recommendation: Ensure UUID column contains valid UUID values.
-- Severity : error
-- Columns  : col_uuid
-- Condition: col_uuid::text !~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.migration_test
WHERE NOT (col_uuid::text !~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$');

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (NOT REGEXP_LIKE(col_uuid, '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'));


-- AI Recommendation: Ensure text columns do not contain excessively long values.
-- Severity : warning
-- Columns  : col_varchar, col_text, col_char, test_label
-- Condition: LENGTH(col_varchar) > 255 OR LENGTH(col_text) > 255 OR LENGTH(col_char) > 255 OR LENGTH(test_label) > 255
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.migration_test
WHERE NOT (LENGTH(col_varchar) > 255 OR LENGTH(col_text) > 255 OR LENGTH(col_char) > 255 OR LENGTH(test_label) > 255);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (LENGTH(col_varchar) > 255 OR LENGTH(col_text) > 255 OR LENGTH(col_char) > 255 OR LENGTH(test_label) > 255);


-- AI Recommendation: Ensure date columns do not contain NULL values if they are expected to represent critical timestamps.
-- Severity : warning
-- Columns  : col_date, col_timestamp_ntz, col_timestamp_tz
-- Condition: col_date IS NULL OR col_timestamp_ntz IS NULL OR col_timestamp_tz IS NULL
-- Run on PostgreSQL:
SELECT COUNT(*) AS violating_rows
FROM public.migration_test
WHERE NOT (col_date IS NULL OR col_timestamp_ntz IS NULL OR col_timestamp_tz IS NULL);

-- Run on Snowflake:
SELECT COUNT(*) AS violating_rows
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE AND NOT (col_date IS NULL OR col_timestamp_ntz IS NULL OR col_timestamp_tz IS NULL);

