-- ======================================================================
-- MIGRATION VALIDATOR — Generated Validation Queries
-- Table        : migration_test
-- Source       : postgresql://public.migration_test
-- Target       : snowflake://DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
-- Generated    : 2026-08-12T17:51:23.174907
-- Generated by : AI
-- AI Model     : gpt-4o
-- Primary Keys : NONE — No primary key detected — duplicate/missing row checks (⑨-⑭) skipped. Declare primary_keys in your batch YAML to enable them.
-- ======================================================================
-- HOW TO USE:
--   ① Run on PostgreSQL  → compare count with ②
--   ② Run on Snowflake   → compare count with ①
--   ③ Run on PostgreSQL  → export to CSV
--   ④ Run on Snowflake   → export to CSV
--   Compare ③ vs ④ row-by-row — must be IDENTICAL
--   ⑤ Run on PostgreSQL  → compare NULL % with ⑥
--   ⑥ Run on Snowflake   → compare NULL % with ⑤
--   ⑦ Run on PostgreSQL  → compare distinct counts with ⑧
--   ⑧ Run on Snowflake   → compare distinct counts with ⑦
-- ======================================================================
-- ──────────────────────────────────────────────────────────────────────
-- ① ROW COUNT — PostgreSQL (Expected: matches ②)
-- ──────────────────────────────────────────────────────────────────────
-- ① ROW COUNT: PostgreSQL (public.migration_test)
SELECT COUNT(*) AS source_row_count
FROM public.migration_test;

-- ──────────────────────────────────────────────────────────────────────
-- ② ROW COUNT — Snowflake  (Expected: matches ①)
-- ──────────────────────────────────────────────────────────────────────
-- ② ROW COUNT: Snowflake (DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST)
SELECT COUNT(*) AS target_row_count
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE;

-- ──────────────────────────────────────────────────────────────────────
-- ③ MAIN VALIDATION — PostgreSQL (normalised data — export CSV, compare with ④)
-- ──────────────────────────────────────────────────────────────────────
-- ③ SOURCE: PostgreSQL (public.migration_test)
SELECT
    COALESCE(CAST(CAST(row_id AS TEXT) AS TEXT), '<<NULL>>') AS row_id_normalized,
    COALESCE(CAST(TRIM(col_varchar) AS TEXT), '<<NULL>>') AS col_varchar_normalized,
    COALESCE(CAST(TRIM(col_text) AS TEXT), '<<NULL>>') AS col_text_normalized,
    COALESCE(CAST(TRIM(col_char) AS TEXT), '<<NULL>>') AS col_char_normalized,
    COALESCE(CAST(CASE WHEN col_boolean = true THEN '1' WHEN col_boolean = false THEN '0' ELSE NULL END AS TEXT), '<<NULL>>') AS col_boolean_normalized,
    COALESCE(CAST(CAST(col_smallint AS TEXT) AS TEXT), '<<NULL>>') AS col_smallint_normalized,
    COALESCE(CAST(CAST(col_integer AS TEXT) AS TEXT), '<<NULL>>') AS col_integer_normalized,
    COALESCE(CAST(CAST(col_bigint AS TEXT) AS TEXT), '<<NULL>>') AS col_bigint_normalized,
    COALESCE(CAST(ROUND(CAST(col_numeric AS NUMERIC), 2) AS TEXT), '<<NULL>>') AS col_numeric_normalized,
    COALESCE(CAST(ROUND(CAST(col_decimal AS NUMERIC), 2) AS TEXT), '<<NULL>>') AS col_decimal_normalized,
    COALESCE(CAST(ROUND(CAST(col_float AS NUMERIC), 2) AS TEXT), '<<NULL>>') AS col_float_normalized,
    COALESCE(CAST(TO_CHAR(col_date, 'YYYY-MM-DD') AS TEXT), '<<NULL>>') AS col_date_normalized,
    COALESCE(CAST(TO_CHAR(col_timestamp_ntz, 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS col_timestamp_ntz_normalized,
    COALESCE(CAST(TO_CHAR(col_timestamp_tz AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') AS TEXT), '<<NULL>>') AS col_timestamp_tz_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(col_uuid AS TEXT))) AS TEXT), '<<NULL>>') AS col_uuid_normalized,
    COALESCE(CAST(col_json::jsonb::text AS TEXT), '<<NULL>>') AS col_json_normalized,
    COALESCE(CAST(col_jsonb::jsonb::text AS TEXT), '<<NULL>>') AS col_jsonb_normalized,
    COALESCE(CAST(encode(col_bytea, 'hex') AS TEXT), '<<NULL>>') AS col_bytea_normalized,
    COALESCE(CAST(TRIM(CAST(col_hstore AS TEXT)) AS TEXT), '<<NULL>>') AS col_hstore_normalized,
    COALESCE(CAST(TRIM(test_label) AS TEXT), '<<NULL>>') AS test_label_normalized
FROM public.migration_test;

-- ──────────────────────────────────────────────────────────────────────
-- ④ MAIN VALIDATION — Snowflake  (normalised data — export CSV, compare with ③)
-- ──────────────────────────────────────────────────────────────────────
-- ④ TARGET: Snowflake (DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST)
SELECT
    COALESCE(CAST(CAST(ROW_ID AS STRING) AS STRING), '<<NULL>>') AS row_id_normalized,
    COALESCE(CAST(TRIM(COL_VARCHAR) AS STRING), '<<NULL>>') AS col_varchar_normalized,
    COALESCE(CAST(TRIM(COL_TEXT) AS STRING), '<<NULL>>') AS col_text_normalized,
    COALESCE(CAST(TRIM(COL_CHAR) AS STRING), '<<NULL>>') AS col_char_normalized,
    COALESCE(CAST(CASE WHEN COL_BOOLEAN = TRUE THEN '1' WHEN COL_BOOLEAN = FALSE THEN '0' ELSE NULL END AS STRING), '<<NULL>>') AS col_boolean_normalized,
    COALESCE(CAST(CAST(COL_SMALLINT AS STRING) AS STRING), '<<NULL>>') AS col_smallint_normalized,
    COALESCE(CAST(CAST(COL_INTEGER AS STRING) AS STRING), '<<NULL>>') AS col_integer_normalized,
    COALESCE(CAST(CAST(COL_BIGINT AS STRING) AS STRING), '<<NULL>>') AS col_bigint_normalized,
    COALESCE(CAST(ROUND(CAST(COL_NUMERIC AS NUMBER(38, 2)), 2) AS STRING), '<<NULL>>') AS col_numeric_normalized,
    COALESCE(CAST(ROUND(CAST(COL_DECIMAL AS NUMBER(38, 2)), 2) AS STRING), '<<NULL>>') AS col_decimal_normalized,
    COALESCE(CAST(ROUND(CAST(COL_FLOAT AS NUMBER(38, 2)), 2) AS STRING), '<<NULL>>') AS col_float_normalized,
    COALESCE(CAST(TO_VARCHAR(COL_DATE, 'YYYY-MM-DD') AS STRING), '<<NULL>>') AS col_date_normalized,
    COALESCE(CAST(TO_VARCHAR(COL_TIMESTAMP_NTZ, 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS col_timestamp_ntz_normalized,
    COALESCE(CAST(TO_VARCHAR(CONVERT_TIMEZONE('UTC', COL_TIMESTAMP_TZ), 'YYYY-MM-DD HH24:MI:SS') AS STRING), '<<NULL>>') AS col_timestamp_tz_normalized,
    COALESCE(CAST(UPPER(TRIM(CAST(COL_UUID AS STRING))) AS STRING), '<<NULL>>') AS col_uuid_normalized,
    COALESCE(CAST(TO_JSON(PARSE_JSON(CAST(COL_JSON AS STRING))) AS STRING), '<<NULL>>') AS col_json_normalized,
    COALESCE(CAST(TO_JSON(PARSE_JSON(CAST(COL_JSONB AS STRING))) AS STRING), '<<NULL>>') AS col_jsonb_normalized,
    COALESCE(CAST(LOWER(HEX_ENCODE(COL_BYTEA)) AS STRING), '<<NULL>>') AS col_bytea_normalized,
    COALESCE(CAST(TRIM(COL_HSTORE) AS STRING), '<<NULL>>') AS col_hstore_normalized,
    COALESCE(CAST(TRIM(TEST_LABEL) AS STRING), '<<NULL>>') AS test_label_normalized
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE;

-- ──────────────────────────────────────────────────────────────────────
-- ⑤ NULL % PER COLUMN — PostgreSQL (compare null_pct values with ⑥)
-- ──────────────────────────────────────────────────────────────────────
-- ⑤ NULL % CHECK: PostgreSQL (public.migration_test)
SELECT
    COUNT(*) AS total_rows,
    ROUND(100.0 * SUM(CASE WHEN row_id IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS row_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_varchar IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_varchar_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_text IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_text_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_char IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_char_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_boolean IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_boolean_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_smallint IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_smallint_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_integer IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_integer_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_bigint IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_bigint_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_numeric IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_numeric_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_decimal IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_decimal_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_float IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_float_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_date IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_date_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_timestamp_ntz IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_timestamp_ntz_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_timestamp_tz IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_timestamp_tz_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_uuid IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_uuid_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_json IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_json_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_jsonb IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_jsonb_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_bytea IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_bytea_null_pct,
    ROUND(100.0 * SUM(CASE WHEN col_hstore IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_hstore_null_pct,
    ROUND(100.0 * SUM(CASE WHEN test_label IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS test_label_null_pct
FROM public.migration_test;

-- ──────────────────────────────────────────────────────────────────────
-- ⑥ NULL % PER COLUMN — Snowflake  (compare null_pct values with ⑤)
-- ──────────────────────────────────────────────────────────────────────
-- ⑥ NULL % CHECK: Snowflake (DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST)
SELECT
    COUNT(*) AS total_rows,
    ROUND(100.0 * SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS row_id_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_VARCHAR IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_varchar_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_TEXT IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_text_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_CHAR IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_char_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_BOOLEAN IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_boolean_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_SMALLINT IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_smallint_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_INTEGER IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_integer_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_BIGINT IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_bigint_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_NUMERIC IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_numeric_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_DECIMAL IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_decimal_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_FLOAT IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_float_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_DATE IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_date_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_TIMESTAMP_NTZ IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_timestamp_ntz_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_TIMESTAMP_TZ IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_timestamp_tz_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_UUID IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_uuid_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_JSON IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_json_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_JSONB IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_jsonb_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_BYTEA IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_bytea_null_pct,
    ROUND(100.0 * SUM(CASE WHEN COL_HSTORE IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS col_hstore_null_pct,
    ROUND(100.0 * SUM(CASE WHEN TEST_LABEL IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS test_label_null_pct
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE;

-- ──────────────────────────────────────────────────────────────────────
-- ⑦ DISTINCT VALUE COUNT — PostgreSQL (compare distinct_count with ⑧)
-- ──────────────────────────────────────────────────────────────────────
-- ⑦ DISTINCT VALUE COUNT: PostgreSQL (public.migration_test)
-- Compare distinct counts with ⑧ — large differences indicate data drift.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT row_id) AS row_id_distinct_count,
    COUNT(DISTINCT col_varchar) AS col_varchar_distinct_count,
    COUNT(DISTINCT col_text) AS col_text_distinct_count,
    COUNT(DISTINCT col_char) AS col_char_distinct_count,
    COUNT(DISTINCT col_boolean) AS col_boolean_distinct_count,
    COUNT(DISTINCT col_smallint) AS col_smallint_distinct_count,
    COUNT(DISTINCT col_integer) AS col_integer_distinct_count,
    COUNT(DISTINCT col_bigint) AS col_bigint_distinct_count,
    COUNT(DISTINCT col_numeric) AS col_numeric_distinct_count,
    COUNT(DISTINCT col_decimal) AS col_decimal_distinct_count,
    COUNT(DISTINCT col_float) AS col_float_distinct_count,
    COUNT(DISTINCT col_date) AS col_date_distinct_count,
    COUNT(DISTINCT col_timestamp_ntz) AS col_timestamp_ntz_distinct_count,
    COUNT(DISTINCT col_timestamp_tz) AS col_timestamp_tz_distinct_count,
    COUNT(DISTINCT col_uuid) AS col_uuid_distinct_count,
    COUNT(DISTINCT col_json::jsonb) AS col_json_distinct_count,
    COUNT(DISTINCT col_jsonb) AS col_jsonb_distinct_count,
    COUNT(DISTINCT col_bytea) AS col_bytea_distinct_count,
    COUNT(DISTINCT col_hstore) AS col_hstore_distinct_count,
    COUNT(DISTINCT test_label) AS test_label_distinct_count
FROM public.migration_test;

-- ──────────────────────────────────────────────────────────────────────
-- ⑧ DISTINCT VALUE COUNT — Snowflake  (compare distinct_count with ⑦)
-- ──────────────────────────────────────────────────────────────────────
-- ⑧ DISTINCT VALUE COUNT: Snowflake (DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST)
-- Compare distinct counts with ⑦ — large differences indicate data drift.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS row_id_distinct_count,
    COUNT(DISTINCT COL_VARCHAR) AS col_varchar_distinct_count,
    COUNT(DISTINCT COL_TEXT) AS col_text_distinct_count,
    COUNT(DISTINCT COL_CHAR) AS col_char_distinct_count,
    COUNT(DISTINCT COL_BOOLEAN) AS col_boolean_distinct_count,
    COUNT(DISTINCT COL_SMALLINT) AS col_smallint_distinct_count,
    COUNT(DISTINCT COL_INTEGER) AS col_integer_distinct_count,
    COUNT(DISTINCT COL_BIGINT) AS col_bigint_distinct_count,
    COUNT(DISTINCT COL_NUMERIC) AS col_numeric_distinct_count,
    COUNT(DISTINCT COL_DECIMAL) AS col_decimal_distinct_count,
    COUNT(DISTINCT COL_FLOAT) AS col_float_distinct_count,
    COUNT(DISTINCT COL_DATE) AS col_date_distinct_count,
    COUNT(DISTINCT COL_TIMESTAMP_NTZ) AS col_timestamp_ntz_distinct_count,
    COUNT(DISTINCT COL_TIMESTAMP_TZ) AS col_timestamp_tz_distinct_count,
    COUNT(DISTINCT COL_UUID) AS col_uuid_distinct_count,
    COUNT(DISTINCT COL_JSON) AS col_json_distinct_count,
    COUNT(DISTINCT COL_JSONB) AS col_jsonb_distinct_count,
    COUNT(DISTINCT COL_BYTEA) AS col_bytea_distinct_count,
    COUNT(DISTINCT COL_HSTORE) AS col_hstore_distinct_count,
    COUNT(DISTINCT TEST_LABEL) AS test_label_distinct_count
FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.MIGRATION_TEST
WHERE _FIVETRAN_ACTIVE = TRUE;
