"""
Query Output Manager
=====================
Orchestrates SQL generation + YAML config writing for one table.

This is the single entry point used by the pipeline to:
  1. Build all validation SQL queries via SQLQueryGenerator
  2. Save combined SQL file  → validation_sql/<table>_validation.sql
  3. Save YAML config file   → validation_sql/<table>_validation.yaml
  4. Return a GenerationResult with paths and summary

PK-Free Design
--------------
Primary key handling is deferred to a future milestone.
All queries are generated without PK-based ORDER BY, duplicate checks,
or missing-row checks. Column ordering follows the schema discovery order.

AI Model Tracking
-----------------
The model used for rule assignment is passed through and embedded in both
the SQL file header comment and the YAML config header.

Usage:
    from generated_queries import QueryOutputManager

    manager = QueryOutputManager()
    result = manager.generate(
        table_name="events",
        pg_schema="public",
        pg_table="events",
        sf_database="dev_edge_bronze",
        sf_schema="storedge_fms_public",
        sf_table="EVENTS",
        mappings=column_rule_mappings,
        has_fivetran_active=True,
        generated_by="AI",
        model_used="gpt-4o",
    )
    print(result.sql_path)   # Path to saved .sql file
    print(result.yaml_path)  # Path to saved .yaml file
    print(result.summary())  # Human-readable summary
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, List, Optional

from ai_transformation.static_rule_mapper import ColumnRuleMapping
from generated_queries.sql_query_generator import SQLQueryGenerator, ValidationQuerySet
from generated_queries.yaml_config_writer import YAMLConfigWriter

if TYPE_CHECKING:
    from core.validation_plan import CanonicalValidationPlan

# Default output directory (project root / validation_sql)
_DEFAULT_OUTPUT_DIR = Path(__file__).parent.parent.parent / "validation_sql"


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------

@dataclass
class GenerationResult:
    """
    Result returned by QueryOutputManager.generate().

    Attributes:
        table_name         : Source table name
        sql_path           : Absolute path to the generated .sql file
        yaml_path          : Absolute path to the generated .yaml file
        query_set          : Full ValidationQuerySet (all SQL strings)
        active_columns     : Number of columns included in validation
        skipped_columns    : Column names excluded (complex types / no match)
        generated_by       : 'AI' or 'static'
        model_used         : AI model name (e.g. 'gpt-4o', 'N/A' for static)
        has_fivetran_active: Whether Snowflake _FIVETRAN_ACTIVE filter was applied
    """
    table_name: str
    sql_path: Path
    yaml_path: Path
    query_set: ValidationQuerySet
    active_columns: int = 0
    skipped_columns: List[str] = field(default_factory=list)
    generated_by: str = "static"
    model_used: str = "N/A"
    has_fivetran_active: bool = False
    dynamic_suite_path: Optional[Path] = None
    dynamic_suite_yaml_path: Optional[Path] = None

    def summary(self) -> str:
        """Return a human-readable generation summary."""
        sep = "=" * 65
        skip_detail = (
            f" ({', '.join(self.skipped_columns)})"
            if self.skipped_columns
            else ""
        )
        fivetran_str = (
            "YES (WHERE _FIVETRAN_ACTIVE = TRUE)"
            if self.has_fivetran_active
            else "NO"
        )
        return (
            f"\n{sep}\n"
            f"  ✅ QUERY GENERATION COMPLETE\n"
            f"{sep}\n"
            f"  Table          : {self.table_name}\n"
            f"  Generated by   : {self.generated_by.upper()}\n"
            f"  AI Model       : {self.model_used}\n"
            f"  Active columns : {self.active_columns}\n"
            f"  Skipped columns: {len(self.skipped_columns)}{skip_detail}\n"
            f"  Fivetran filter: {fivetran_str}\n"
            f"\n"
            f"  💾 SQL  : {self.sql_path}\n"
            f"  📋 YAML : {self.yaml_path}\n"
            f"{sep}"
        )


# ---------------------------------------------------------------------------
# Query Output Manager
# ---------------------------------------------------------------------------

class QueryOutputManager:
    """
    Orchestrates SQL generation + file output for a single table pair.

    Produces two files per table:
      <table>_validation.sql   — all 6 validation queries (no PK queries)
      <table>_validation.yaml  — YAML config for automated validation runners
    """

    def __init__(self, output_dir: Optional[Path] = None):
        """
        Args:
            output_dir: Directory for output files (default: validation_sql/)
        """
        self._output_dir  = output_dir or _DEFAULT_OUTPUT_DIR
        self._sql_gen     = SQLQueryGenerator()
        self._yaml_writer = YAMLConfigWriter()

    def generate(
        self,
        table_name: str,
        pg_schema: str,
        pg_table: str,
        sf_database: str,
        sf_schema: str,
        sf_table: str,
        mappings: List[ColumnRuleMapping],
        has_fivetran_active: bool = False,
        generated_by: str = "static",
        model_used: str = "N/A",
    ) -> GenerationResult:
        """
        Generate all validation output for one table pair.

        Args:
            table_name         : Display name for the table (used in file names)
            pg_schema          : PostgreSQL schema (e.g. 'public')
            pg_table           : PostgreSQL table name
            sf_database        : Snowflake database name
            sf_schema          : Snowflake schema name
            sf_table           : Snowflake table name (UPPER recommended)
            mappings           : Column rule mappings from ai_transformation
            has_fivetran_active: Add WHERE _FIVETRAN_ACTIVE = TRUE on Snowflake side
            generated_by       : 'AI' or 'static'
            model_used         : AI model name used (e.g. 'gpt-4o')

        Returns:
            GenerationResult with sql_path, yaml_path, and summary stats.
        """
        self._output_dir.mkdir(parents=True, exist_ok=True)

        active  = [m for m in mappings if not m.skip_validation]
        skipped = [m.source_column for m in mappings if m.skip_validation]

        print(f"\n  [QueryOutputManager] Generating output for '{table_name}'...")
        print(f"    Active columns  : {len(active)}")
        print(f"    Skipped columns : {len(skipped)}")
        print(f"    Fivetran filter : {has_fivetran_active}")
        print(f"    Generated by    : {generated_by} (model: {model_used})")

        # ── Step 1: Generate all SQL queries ─────────────────────────────────
        query_set = self._sql_gen.generate(
            pg_schema=pg_schema,
            pg_table=pg_table,
            sf_database=sf_database,
            sf_schema=sf_schema,
            sf_table=sf_table,
            mappings=active,
            has_fivetran_active=has_fivetran_active,
            generated_by=generated_by,
            model_used=model_used,
        )

        # ── Step 2: Save combined SQL file ────────────────────────────────────
        sql_path = self._save_sql(query_set, pg_table)

        # ── Step 3: Save YAML config file ─────────────────────────────────────
        yaml_path = self._yaml_writer.write(
            query_set=query_set,
            pg_schema=pg_schema,
            pg_table=pg_table,
            sf_database=sf_database,
            sf_schema=sf_schema,
            sf_table=sf_table,
            mappings=active,
            has_fivetran_active=has_fivetran_active,
            output_dir=self._output_dir,
        )

        result = GenerationResult(
            table_name=table_name,
            sql_path=sql_path,
            yaml_path=yaml_path,
            query_set=query_set,
            active_columns=len(active),
            skipped_columns=skipped,
            generated_by=generated_by,
            model_used=model_used,
            has_fivetran_active=has_fivetran_active,
        )

        print(result.summary())
        return result

    # -----------------------------------------------------------------------
    # Private helpers
    # -----------------------------------------------------------------------

    def generate_from_plan(self, plan: "CanonicalValidationPlan") -> GenerationResult:
        """
        Generate all validation output from a CanonicalValidationPlan.

        This is the new plan-driven entry point. Both SQL and YAML are
        generated from the same plan object — guaranteed to be in sync.

        Args:
            plan: Fully validated CanonicalValidationPlan

        Returns:
            GenerationResult with sql_path, yaml_path, and summary stats.
        """
        self._output_dir.mkdir(parents=True, exist_ok=True)

        active  = plan.active_mappings
        skipped = plan.skipped_mappings

        print(f"\n  [QueryOutputManager] Generating output from plan for '{plan.source_table}'...")
        print(f"    Active columns  : {len(active)}")
        print(f"    Skipped columns : {len(skipped)}")
        print(f"    Fivetran filter : {plan.has_fivetran_active}")
        print(f"    Generated by    : {plan.generated_by} (model: {plan.model_used})")
        print(f"    Exact matches   : {len(plan.exact_matches)}")
        print(f"    Fuzzy matches   : {len(plan.fuzzy_matches)}")
        print(f"    AI-resolved     : {len(plan.ai_resolved_matches)}")

        # ── SQL and YAML from the same plan ───────────────────────────────────
        query_set = self._sql_gen.generate_from_plan(plan)
        sql_path  = self._save_sql(query_set, plan.source_table)
        yaml_path = self._yaml_writer.write_from_plan(plan, query_set, self._output_dir)

        skipped_names = [m.source_column for m in skipped]
        result = GenerationResult(
            table_name=plan.source_table,
            sql_path=sql_path,
            yaml_path=yaml_path,
            query_set=query_set,
            active_columns=len(active),
            skipped_columns=skipped_names,
            generated_by=plan.generated_by,
            model_used=plan.model_used,
            has_fivetran_active=plan.has_fivetran_active,
        )
        print(result.summary())
        return result

    def _save_sql(self, query_set: ValidationQuerySet, table_name: str) -> Path:
        """Save the combined SQL validation file to disk."""
        sql_path = self._output_dir / f"{table_name.lower()}_validation.sql"
        with open(sql_path, "w", encoding="utf-8") as f:
            f.write(query_set.combined_sql)
        print(f"  💾 SQL  saved : {sql_path.resolve()}")
        return sql_path
