"""
AI Query Agent — DIAL-backed assistant for migration validation.

Responsibilities
----------------
1. Read rules_catalog.json to know what rules exist and when to apply them.
2. Accept schema metadata (source + target column lists) from the caller.
3. Build a carefully structured prompt and call the DIAL API
   (OpenAI-compatible endpoint) to get rule assignments + SQL queries.
4. Parse the JSON response into ColumnMapping objects the rest of the
   framework can consume directly.
5. Graceful fallback: if DIAL_API_KEY is not set, apply rules using the
   static rule-matching logic already in transformation_rules.py.

Environment variables
---------------------
DIAL_API_KEY      — required for AI mode
DIAL_API_BASE     — defaults to https://ai-proxy.lab.epam.com  (EPAM VPN required)
DIAL_API_VERSION  — Azure OpenAI api-version, defaults to 2025-04-01-preview
DIAL_MODEL        — deployment name, defaults to gpt-4o

Usage (programmatic)
--------------------
    from ai_query_agent import AIQueryAgent
    from models import DatabaseType

    agent = AIQueryAgent()
    result = agent.generate_validation_plan(
        source_db_type=DatabaseType.POSTGRESQL,
        source_schema="source_data",
        source_table="users",
        source_columns=[{"column_name": "user_id", "data_type": "SERIAL", ...}, ...],
        target_db_type=DatabaseType.SNOWFLAKE,
        target_schema="target_schema",
        target_table="USERS",
        target_columns=[{"column_name": "USER_ID", "data_type": "NUMBER", ...}, ...],
        target_database="snowflake_db",
    )
    # result.source_sql  — ready to run on source DB
    # result.target_sql  — ready to run on target DB (Snowflake)
    # result.column_mappings  — list of ColumnMapping dataclass instances
    # result.rules_applied  — dict of col -> [rule_ids]
    # result.explanation  — human-readable reasoning from the AI
"""

import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from models import (
    ColumnMapping,
    DatabaseType,
    TransformationRuleType,
)
from schema_discovery import ColumnInfo, column_info_to_dict
from sql_generators import query_generator
from transformation_rules import rules_engine

# ---------------------------------------------------------------------------
# Constants / paths
# ---------------------------------------------------------------------------

_CATALOG_PATH = Path(__file__).parent / "rules_catalog.json"
_DEFAULT_API_BASE = "https://ai-proxy.lab.epam.com"
_DEFAULT_API_VERSION = "2025-04-01-preview"
_DEFAULT_MODEL = "gpt-4o"


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class ValidationPlan:
    """Everything the AI agent produces for a single source→target table pair."""
    source_db_type: DatabaseType
    target_db_type: DatabaseType
    source_schema: str
    source_table: str
    target_schema: str
    target_table: str
    target_database: Optional[str]

    column_mappings: List[ColumnMapping] = field(default_factory=list)
    rules_applied: Dict[str, List[str]] = field(default_factory=dict)
    source_sql: str = ""
    target_sql: str = ""
    explanation: str = ""
    generated_by: str = "static"  # "ai" | "static"

    def print_summary(self):
        """Pretty-print plan to stdout."""
        sep = "=" * 70
        print(f"\n{sep}")
        print(f"  VALIDATION PLAN  |  {self.source_table} → {self.target_table}")
        print(sep)
        print(f"  Generated by : {self.generated_by.upper()}")
        print(f"  Source       : {self.source_db_type.value}.{self.source_schema}.{self.source_table}")
        tf = f"{self.target_database + '.' if self.target_database else ''}{self.target_schema}.{self.target_table}"
        print(f"  Target       : {self.target_db_type.value}.{tf}")
        print(f"\n  Column mappings ({len(self.column_mappings)}):")
        for cm in self.column_mappings:
            rules = ", ".join(r.value for r in cm.apply_rules) or "none"
            pk = " [PK]" if cm.primary_key else ""
            print(f"    {cm.source_column}({cm.source_data_type}){pk} -> {cm.target_column}({cm.target_data_type})  rules: [{rules}]")
        if self.explanation:
            print(f"\n  AI reasoning:\n    {self.explanation[:400]}")
        print(f"\n{'─' * 70}")
        print("  SOURCE SQL:")
        print(f"{'─' * 70}")
        print(self.source_sql)
        print(f"\n{'─' * 70}")
        print("  TARGET SQL:")
        print(f"{'─' * 70}")
        print(self.target_sql)
        print(sep)


# ---------------------------------------------------------------------------
# Catalog loader
# ---------------------------------------------------------------------------

class RulesCatalog:
    """Thin wrapper around rules_catalog.json."""

    def __init__(self, path: Path = _CATALOG_PATH):
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        self._rules: List[Dict[str, Any]] = data["rules"]
        self._chain_order: List[str] = data.get("chaining_order", [])
        # Build lookup: enum_value -> rule dict
        self._by_enum: Dict[str, Dict[str, Any]] = {r["enum_value"]: r for r in self._rules}

    def all_rules(self) -> List[Dict[str, Any]]:
        return self._rules

    def prompt_summary(self) -> str:
        """Compact representation of all rules to inject into the system prompt."""
        lines = []
        for r in self._rules:
            triggers = ", ".join(
                f"{p['source']}→{p['target']}" for p in r["trigger_type_pairs"]
            )
            lines.append(
                f"- {r['enum_value']}: {r['description']}  "
                f"[auto_detect={r['auto_detect']}]  triggers on: {triggers}"
            )
        return "\n".join(lines)

    def enum_value_to_rule_type(self, enum_value: str) -> Optional[TransformationRuleType]:
        try:
            return TransformationRuleType(enum_value.lower())
        except ValueError:
            return None

    def chain_order(self) -> List[str]:
        return self._chain_order


_catalog = RulesCatalog()


# ---------------------------------------------------------------------------
# Static fallback rule-matching (no AI required)
# ---------------------------------------------------------------------------

def _static_rule_match(source_type: str, target_type: str) -> List[TransformationRuleType]:
    """
    Apply the catalog's auto_detect logic to pick rules for a type pair.
    Returns a list of TransformationRuleType values in chaining order.
    """
    matched: List[TransformationRuleType] = []
    src_up = source_type.upper()
    tgt_up = target_type.upper()

    # Strip width/precision modifiers for matching: VARCHAR(100) -> VARCHAR
    src_base = re.sub(r"\(.*\)", "", src_up).strip()
    tgt_base = re.sub(r"\(.*\)", "", tgt_up).strip()

    for rule_def in _catalog.all_rules():
        if not rule_def.get("auto_detect"):
            continue
        for pair in rule_def["trigger_type_pairs"]:
            s, t = pair["source"].upper(), pair["target"].upper()
            # Wildcard pair ("*") matches everything
            if s == "*" or t == "*":
                rt = _catalog.enum_value_to_rule_type(rule_def["enum_value"])
                if rt and rt not in matched:
                    matched.append(rt)
                break
            if src_base.startswith(s) and tgt_base.startswith(t):
                rt = _catalog.enum_value_to_rule_type(rule_def["enum_value"])
                if rt and rt not in matched:
                    matched.append(rt)
                break

    # Sort by chain order
    chain = _catalog.chain_order()
    matched.sort(key=lambda r: chain.index(r.value) if r.value in chain else len(chain))
    return matched


# ---------------------------------------------------------------------------
# Column matcher (by name, case-insensitive)
# ---------------------------------------------------------------------------

def _match_columns(
    source_cols: List[Dict[str, Any]],
    target_cols: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Pair source and target columns by normalised name.
    Returns list of {"source": col_dict, "target": col_dict} pairs.
    Unmatched columns are logged but not included.
    """
    tgt_by_name = {c["column_name"].upper(): c for c in target_cols}
    pairs = []
    for sc in source_cols:
        key = sc["column_name"].upper()
        tc = tgt_by_name.get(key)
        if tc:
            pairs.append({"source": sc, "target": tc})
        else:
            print(f"  [WARN] No target column found for source '{sc['column_name']}' — skipped", file=sys.stderr)
    return pairs


# ---------------------------------------------------------------------------
# AI Query Agent
# ---------------------------------------------------------------------------

class AIQueryAgent:
    """
    Generates migration validation SQL using DIAL (OpenAI-compatible API).

    Falls back to static rule matching when DIAL_API_KEY is not set or the
    API call fails.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_base: Optional[str] = None,
        api_version: Optional[str] = None,
        model: Optional[str] = None,
    ):
        self.api_key = api_key or os.getenv("DIAL_API_KEY", "")
        self.api_base = api_base or os.getenv("DIAL_API_BASE", _DEFAULT_API_BASE)
        self.api_version = api_version or os.getenv("DIAL_API_VERSION", _DEFAULT_API_VERSION)
        self.model = model or os.getenv("DIAL_MODEL", _DEFAULT_MODEL)
        self._ai_available = bool(self.api_key)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def generate_validation_plan(
        self,
        source_db_type: DatabaseType,
        source_schema: str,
        source_table: str,
        source_columns: List[Dict[str, Any]],
        target_db_type: DatabaseType,
        target_schema: str,
        target_table: str,
        target_columns: List[Dict[str, Any]],
        target_database: Optional[str] = None,
        primary_key_hints: Optional[List[str]] = None,
    ) -> ValidationPlan:
        """
        Main entry point.  Accepts raw column metadata dicts
        (as returned by schema_discovery.column_info_to_dict) and
        produces a complete ValidationPlan.
        """
        plan = ValidationPlan(
            source_db_type=source_db_type,
            target_db_type=target_db_type,
            source_schema=source_schema,
            source_table=source_table,
            target_schema=target_schema,
            target_table=target_table,
            target_database=target_database,
        )

        pairs = _match_columns(source_columns, target_columns)

        if self._ai_available:
            plan = self._generate_with_ai(plan, pairs, primary_key_hints or [])
        else:
            print("  [INFO] DIAL_API_KEY not set — using static rule matching.", file=sys.stderr)
            plan = self._generate_static(plan, pairs, primary_key_hints or [])

        plan.source_sql, plan.target_sql = self._build_sql(plan)
        return plan

    # ------------------------------------------------------------------
    # AI path
    # ------------------------------------------------------------------

    def _generate_with_ai(
        self,
        plan: ValidationPlan,
        pairs: List[Dict[str, Any]],
        pk_hints: List[str],
    ) -> ValidationPlan:
        try:
            from openai import AzureOpenAI  # type: ignore
        except ImportError:
            print("  [WARN] 'openai' package not installed. pip install openai>=1.0. Falling back to static.", file=sys.stderr)
            return self._generate_static(plan, pairs, pk_hints)

        # DIAL uses the AzureOpenAI client; Api-Key header is passed via api_key.
        client = AzureOpenAI(
            api_key=self.api_key,
            api_version=self.api_version,
            azure_endpoint=self.api_base,
        )

        system_prompt = self._build_system_prompt()
        user_prompt = self._build_user_prompt(plan, pairs, pk_hints)

        try:
            response = client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user",   "content": user_prompt},
                ],
                temperature=0,
                response_format={"type": "json_object"},
                extra_headers={"Api-Key": self.api_key},
            )
            raw = response.choices[0].message.content
            return self._parse_ai_response(plan, raw, pairs)
        except Exception as exc:
            print(f"  [WARN] DIAL API error: {exc}. Falling back to static.", file=sys.stderr)
            return self._generate_static(plan, pairs, pk_hints)

    def _build_system_prompt(self) -> str:
        catalog_text = _catalog.prompt_summary()
        return f"""You are a Senior Data Migration QA Engineer specialising in SQL validation.
You are helping validate data migrated from PostgreSQL (source) to Snowflake (target).

Your task is to analyse source and target column metadata and produce a JSON validation plan
that ensures DATA COMPLETENESS — meaning every row and column value that existed in the
source is present and correct in the target after migration.

## Data Completeness Checks Required
For each column mapping you produce, the generated SQL must support:
  1. ROW COUNT match     — total rows in source must equal total rows in target
  2. NULL percentage     — % of NULLs per column must match (within tolerance)
  3. DISTINCT value count— cardinality of each column must match
  4. TYPE-SAFE comparison— values normalised for type differences before comparison
  5. PK coverage         — every source primary key must exist in target

## Available Transformation Rules
{catalog_text}

## Chaining Order
When multiple rules apply to the same column, apply them in this order:
{', '.join(_catalog.chain_order())}

## PostgreSQL → Snowflake Type Mapping Reference
  PostgreSQL         Snowflake           Rules to Apply
  ─────────────────────────────────────────────────────
  SERIAL / BIGSERIAL → NUMBER            INTEGER_CAST
  INTEGER / INT      → NUMBER            INTEGER_CAST
  VARCHAR(n) / TEXT  → VARCHAR / STRING  WHITESPACE_TRIM, CASE_INSENSITIVE, EMPTY_STRING_NULL
  BOOLEAN            → BOOLEAN           BOOLEAN_CONVERSION
  NUMERIC(p,s)       → NUMBER(p,s)       NUMERIC_PRECISION
  DATE               → DATE              DATE_STANDARDIZATION
  TIMESTAMP          → TIMESTAMP_NTZ     DATE_STANDARDIZATION
  TIMESTAMP with TZ  → TIMESTAMP_TZ      DATE_STANDARDIZATION
  JSONB / JSON       → VARIANT           (mark ignore_validation: true — manual check needed)
  ARRAY              → ARRAY / VARIANT   (mark ignore_validation: true — manual check needed)
  BYTEA              → BINARY            (mark ignore_validation: true — binary data)
  UUID               → VARCHAR           WHITESPACE_TRIM
  HSTORE             → VARCHAR / TEXT    (CAST to TEXT before TRIM — hstore type cannot be passed to TRIM directly)
  HSTORE             → VARCHAR / TEXT    CAST to TEXT first, then TRIM (hstore needs explicit CAST before string functions)

## Output contract
You MUST return a single valid JSON object with this exact shape:

{{
  "column_mappings": [
    {{
      "source_column": "string",
      "target_column": "string",
      "source_data_type": "string",
      "target_data_type": "string",
      "primary_key": true | false,
      "ignore_validation": false,
      "apply_rules": ["RULE_ENUM_VALUE", ...]
    }}
  ],
  "explanation": "concise reasoning for the rule selections and completeness strategy"
}}

Strict Rules:
- apply_rules must only contain enum values from the catalog above.
- Do NOT invent rules not in the catalog.
- NULL_STANDARDIZATION must be the LAST rule applied (outermost wrapper) for nullable columns.
- Boolean columns: apply BOOLEAN_CONVERSION. Source BIT(0/1) → Target BOOLEAN(TRUE/FALSE).
- SERIAL/INTEGER source columns: always apply INTEGER_CAST when mapping to Snowflake NUMBER.
- String columns: apply WHITESPACE_TRIM + CASE_INSENSITIVE + NULL_STANDARDIZATION minimum.
- Set primary_key: true for the column(s) that uniquely identify rows (usually *_id columns).
- If a column type is JSONB, ARRAY, BYTEA or XML, set ignore_validation: true (cannot be normalised).
- If a column type is HSTORE, use CAST({col} AS TEXT) BEFORE applying TRIM — PostgreSQL TRIM() cannot accept hstore type directly.
- Prefer correctness over brevity — include all applicable rules rather than fewer.
"""

    def _build_user_prompt(
        self,
        plan: ValidationPlan,
        pairs: List[Dict[str, Any]],
        pk_hints: List[str],
    ) -> str:
        pairs_json = json.dumps(pairs, indent=2)
        pk_hint_text = f"Primary key hints (from user): {pk_hints}" if pk_hints else ""
        source_col_count = len(pairs)
        return f"""Generate a DATA COMPLETENESS validation plan for this PostgreSQL → Snowflake migration.

Source DB  : {plan.source_db_type.value}
Source     : {plan.source_schema}.{plan.source_table}
Target DB  : {plan.target_db_type.value}
Target     : {(plan.target_database + '.') if plan.target_database else ''}{plan.target_schema}.{plan.target_table}
Total cols : {source_col_count} column pairs to map
{pk_hint_text}

Validation Goals:
  1. Every source row must exist in the target (by primary key).
  2. Every source column value must match the target after type normalization.
  3. NULL patterns must be preserved — source NULL % ≈ target NULL %.
  4. No duplicate primary keys should exist in the target.
  5. Distinct value counts per column should match (or be explained).

Column pairs (source PostgreSQL → target Snowflake metadata):
{pairs_json}

For EACH column pair:
  - Choose rules based on the type mapping reference in the system prompt.
  - Mark primary_key: true for identifier columns (usually ending in _id or named id).
  - For complex types (JSONB, ARRAY, BYTEA), set ignore_validation: true.
  - The explanation field should describe your completeness strategy for this table.

Return the complete JSON validation plan.
"""

    def _parse_ai_response(
        self,
        plan: ValidationPlan,
        raw_json: str,
        pairs: List[Dict[str, Any]],
    ) -> ValidationPlan:
        try:
            data = json.loads(raw_json)
        except json.JSONDecodeError as exc:
            print(f"  [WARN] Could not parse AI JSON response: {exc}. Falling back to static.", file=sys.stderr)
            return self._generate_static(plan, pairs, [])

        plan.explanation = data.get("explanation", "")
        plan.generated_by = "ai"

        for cm_dict in data.get("column_mappings", []):
            rule_types: List[TransformationRuleType] = []
            for rule_str in cm_dict.get("apply_rules", []):
                rt = _catalog.enum_value_to_rule_type(rule_str)
                if rt:
                    rule_types.append(rt)
                else:
                    print(f"  [WARN] AI returned unknown rule '{rule_str}' — ignored.", file=sys.stderr)

            plan.column_mappings.append(ColumnMapping(
                source_column=cm_dict["source_column"],
                target_column=cm_dict["target_column"],
                source_data_type=cm_dict.get("source_data_type", ""),
                target_data_type=cm_dict.get("target_data_type", ""),
                apply_rules=rule_types,
                primary_key=cm_dict.get("primary_key", False),
                ignore_validation=cm_dict.get("ignore_validation", False),
            ))

        plan.rules_applied = {
            cm.source_column: [r.value for r in cm.apply_rules]
            for cm in plan.column_mappings
        }
        return plan

    # ------------------------------------------------------------------
    # Static fallback path
    # ------------------------------------------------------------------

    def _generate_static(
        self,
        plan: ValidationPlan,
        pairs: List[Dict[str, Any]],
        pk_hints: List[str],
    ) -> ValidationPlan:
        pk_hints_up = [h.upper() for h in pk_hints]
        for pair in pairs:
            sc = pair["source"]
            tc = pair["target"]
            rules = _static_rule_match(sc["data_type"], tc["data_type"])
            is_pk = sc["column_name"].upper() in pk_hints_up
            plan.column_mappings.append(ColumnMapping(
                source_column=sc["column_name"],
                target_column=tc["column_name"],
                source_data_type=sc["data_type"],
                target_data_type=tc["data_type"],
                apply_rules=rules,
                primary_key=is_pk,
            ))

        plan.rules_applied = {
            cm.source_column: [r.value for r in cm.apply_rules]
            for cm in plan.column_mappings
        }
        plan.generated_by = "static"
        plan.explanation = (
            "Rules assigned by static type-pair matching against rules_catalog.json. "
            "Set DIAL_API_KEY to use AI-based analysis."
        )
        return plan

    # ------------------------------------------------------------------
    # SQL generation
    # ------------------------------------------------------------------

    def _build_sql(self, plan: ValidationPlan) -> tuple:
        """Generate source and target validation SQL from the plan's column mappings."""
        active = [cm for cm in plan.column_mappings if not cm.ignore_validation]

        src_gen = query_generator.get_generator(plan.source_db_type)
        tgt_gen = query_generator.get_generator(plan.target_db_type)

        if plan.source_db_type == DatabaseType.SNOWFLAKE:
            src_sql = src_gen.generate_data_query(
                plan.target_database or "",
                plan.source_schema,
                plan.source_table,
                active,
            )
        else:
            src_sql = src_gen.generate_data_query(
                plan.source_schema,
                plan.source_table,
                active,
            )

        if plan.target_db_type == DatabaseType.SNOWFLAKE:
            tgt_sql = tgt_gen.generate_data_query(
                plan.target_database or "",
                plan.target_schema,
                plan.target_table,
                active,
            )
        else:
            tgt_sql = tgt_gen.generate_data_query(
                plan.target_schema,
                plan.target_table,
                active,
            )

        return src_sql, tgt_sql
