"""
Query Builder — AI-Powered SQL Query Generator (Output Only)
=============================================================
Takes database/schema/table as input.
Connects to PostgreSQL + Snowflake to extract REAL column metadata.
Sends everything to AI (GPT-4o via DIAL).
OUTPUT = Ready-to-run SQL queries for both source and target.

You copy those queries and run them yourself in your SQL client.
Nothing is executed here.

Flow
----
  1. Connect to PostgreSQL  → fetch column metadata
  2. Connect to Snowflake   → fetch column metadata
  3. Inject column metadata + full rule book into AI prompt
  4. AI returns: column mappings + rules to apply per column
  5. SQL generator builds the final normalised queries
  6. Queries printed to terminal + saved to validation_sql/

Usage (programmatic)
--------------------
  from query_builder import QueryBuilder

  builder = QueryBuilder()
  result = builder.build(
      pg_database="fms",
      pg_schema="public",
      pg_table="events",
      sf_schema="storedge_fms_public",
      sf_table="EVENTS",
      primary_keys=["event_id"],
  )
  # result.source_sql  ← run this on PostgreSQL
  # result.target_sql  ← run this on Snowflake
  # result.extra_queries  ← row count, null %, duplicate PK queries
"""

import json
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

# Ensure .env loaded
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent.parent / ".env")
except ImportError:
    pass

from models import ColumnMapping, DatabaseType, TransformationRuleType
from schema_extractor import PostgresSchemaExtractor, SnowflakeSchemaExtractor, SchemaComparator
from schema_discovery import ColumnInfo, column_info_to_dict
from sql_generators import query_generator
from transformation_rules import rules_engine
from rule_book import rule_book, RuleEntry

_DEFAULT_API_BASE    = "https://ai-proxy.lab.epam.com"
_DEFAULT_API_VERSION = "2025-04-01-preview"
_DEFAULT_MODEL       = "gpt-4o"


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------

@dataclass
class QueryResult:
    """All queries generated for one source→target table pair."""
    table_name: str
    source_db: str
    target_db: str
    generated_by: str = "static"     # "ai" | "static"
    ai_explanation: str = ""

    # ── Primary validation queries ──────────────────────────────────────────
    source_sql: str = ""             # Run on PostgreSQL
    target_sql: str = ""             # Run on Snowflake

    # ── Supporting completeness queries ─────────────────────────────────────
    row_count_source_sql: str = ""   # COUNT(*) on source
    row_count_target_sql: str = ""   # COUNT(*) on target
    null_check_source_sql: str = ""  # NULL % per column — source
    null_check_target_sql: str = ""  # NULL % per column — target
    duplicate_pk_sql: str = ""       # Duplicate PK check on target
    missing_rows_sql: str = ""       # Rows in source missing from target

    column_mappings: List[ColumnMapping] = field(default_factory=list)
    skipped_columns: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    def print_queries(self):
        """Pretty-print all queries to stdout."""
        sep = "=" * 70
        thin = "─" * 70

        print(f"\n{sep}")
        print(f"  📋 VALIDATION QUERIES  |  {self.table_name}")
        print(f"  Generated by : {self.generated_by.upper()}")
        print(f"  Source DB    : {self.source_db}")
        print(f"  Target DB    : {self.target_db}")
        print(sep)

        if self.ai_explanation:
            print(f"\n  💡 AI Reasoning:\n  {self.ai_explanation[:500]}")

        print(f"\n{thin}")
        print(f"  ① ROW COUNT — Run on PostgreSQL")
        print(thin)
        print(self.row_count_source_sql)

        print(f"\n{thin}")
        print(f"  ② ROW COUNT — Run on Snowflake")
        print(thin)
        print(self.row_count_target_sql)

        print(f"\n{thin}")
        print(f"  ③ MAIN VALIDATION QUERY — Run on PostgreSQL  (normalised data)")
        print(thin)
        if self.source_sql:
            print(self.source_sql)
        else:
            print("  -- ⚠ No source SQL generated.")
            print("  -- This means all column mappings were skipped (complex types)")
            print("  -- or the AI returned rule names that could not be resolved.")
            print(f"  -- Column mappings received: {len(self.column_mappings)}")
            print(f"  -- Skipped columns: {self.skipped_columns}")

        print(f"\n{thin}")
        print(f"  ④ MAIN VALIDATION QUERY — Run on Snowflake  (normalised data)")
        print(thin)
        if self.target_sql:
            print(self.target_sql)
        else:
            print("  -- ⚠ No target SQL generated.")
            print("  -- Check that active (non-skipped) column mappings exist.")

        if self.null_check_source_sql:
            print(f"\n{thin}")
            print(f"  ⑤ NULL % CHECK — Run on PostgreSQL")
            print(thin)
            print(self.null_check_source_sql)

        if self.null_check_target_sql:
            print(f"\n{thin}")
            print(f"  ⑥ NULL % CHECK — Run on Snowflake")
            print(thin)
            print(self.null_check_target_sql)

        if self.duplicate_pk_sql:
            print(f"\n{thin}")
            print(f"  ⑦ DUPLICATE PK CHECK — Run on Snowflake")
            print(thin)
            print(self.duplicate_pk_sql)

        if self.missing_rows_sql:
            print(f"\n{thin}")
            print(f"  ⑧ MISSING ROWS CHECK — Run on PostgreSQL")
            print(thin)
            print(self.missing_rows_sql)

        if self.skipped_columns:
            print(f"\n  ⚠️  Skipped columns (complex types — manual review needed):")
            for col in self.skipped_columns:
                print(f"       • {col}")

        print(f"\n{sep}")
        print(f"  ✅  Copy the queries above and run them in your SQL client.")
        print(f"  📊  Compare ③ vs ④ results to validate data completeness.")
        print(sep)


# ---------------------------------------------------------------------------
# Query Builder
# ---------------------------------------------------------------------------

class QueryBuilder:
    """
    Connects to source + target, extracts schema, asks AI for rules,
    builds and returns all validation SQL — without executing any of it.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_base: Optional[str] = None,
        api_version: Optional[str] = None,
        model: Optional[str] = None,
    ):
        self.api_key     = api_key     or os.getenv("DIAL_API_KEY", "")
        self.api_base    = api_base    or os.getenv("DIAL_API_BASE", _DEFAULT_API_BASE)
        self.api_version = api_version or os.getenv("DIAL_API_VERSION", _DEFAULT_API_VERSION)
        self.model       = model       or os.getenv("DIAL_MODEL", _DEFAULT_MODEL)
        self._ai_active  = bool(self.api_key)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def build(
        self,
        pg_database: str,
        pg_schema: str,
        pg_table: str,
        sf_schema: str,
        sf_table: str,
        sf_database: Optional[str] = None,
        primary_keys: Optional[List[str]] = None,
        save_sql: bool = True,
    ) -> QueryResult:
        """
        Main entry point.

        Args:
            pg_database  : PostgreSQL database name
            pg_schema    : PostgreSQL schema (e.g. 'public')
            pg_table     : Source table name
            sf_schema    : Snowflake schema
            sf_table     : Snowflake table name (UPPER CASE recommended)
            sf_database  : Snowflake database (default: SNOWFLAKE_DATABASE env var)
            primary_keys : PK column names (auto-detected if empty)
            save_sql     : Save generated SQL to validation_sql/ folder

        Returns:
            QueryResult with all generated SQL strings
        """
        _sf_db = sf_database or os.getenv("SNOWFLAKE_DATABASE", "")

        result = QueryResult(
            table_name=pg_table,
            source_db=f"postgresql://{pg_database}.{pg_schema}.{pg_table}",
            target_db=f"snowflake://{_sf_db}.{sf_schema}.{sf_table}",
        )

        # ── Step 1: Extract schemas ──────────────────────────────────────────
        print(f"\n  [1/3] Connecting to databases and extracting schemas...")
        try:
            pg_ext = PostgresSchemaExtractor(database=pg_database)
            sf_ext = SnowflakeSchemaExtractor(database=_sf_db)
            src_cols = pg_ext.extract_columns(pg_schema, pg_table)
            tgt_cols = sf_ext.extract_columns(sf_schema, sf_table)
        except Exception as exc:
            print(f"  ✗ Schema extraction failed: {exc}")
            raise

        # Schema comparison (informational)
        comparison = SchemaComparator.compare(
            source_columns=src_cols,
            target_columns=tgt_cols,
            source_table=f"{pg_schema}.{pg_table}",
            target_table=f"{sf_schema}.{sf_table}",
        )
        comparison.print_summary()

        # Auto-detect PKs if not provided
        pks = primary_keys or []
        if not pks:
            pks = _auto_detect_pks(src_cols)
            if pks:
                print(f"  [PK auto-detected] {pks}")

        # ── Step 2: Get column mappings from AI ──────────────────────────────
        print(f"\n  [2/3] Asking AI to assign transformation rules...")
        src_dicts = [column_info_to_dict(c) for c in src_cols]
        tgt_dicts = [column_info_to_dict(c) for c in tgt_cols]

        mappings, explanation, generated_by = self._get_mappings(
            src_dicts, tgt_dicts,
            pg_schema, pg_table,
            sf_schema, sf_table, _sf_db,
            pks,
        )
        result.column_mappings = mappings
        result.ai_explanation  = explanation
        result.generated_by    = generated_by

        # Collect skipped columns
        result.skipped_columns = [
            cm.source_column for cm in mappings if cm.ignore_validation
        ]

        # ── Step 3: Build all SQL queries ────────────────────────────────────
        print(f"\n  [3/3] Generating validation SQL queries...")
        active_mappings = [cm for cm in mappings if not cm.ignore_validation]
        pk_cols = [cm.source_column for cm in mappings if cm.primary_key]

        result.source_sql = _build_source_sql(pg_schema, pg_table, active_mappings, pk_cols)
        result.target_sql = _build_target_sql(_sf_db, sf_schema, sf_table, active_mappings, pk_cols)

        result.row_count_source_sql = _row_count_sql_pg(pg_schema, pg_table)
        result.row_count_target_sql = _row_count_sql_sf(_sf_db, sf_schema, sf_table)

        result.null_check_source_sql = _null_check_sql_pg(pg_schema, pg_table, active_mappings)
        result.null_check_target_sql = _null_check_sql_sf(_sf_db, sf_schema, sf_table, active_mappings)

        if pk_cols:
            result.duplicate_pk_sql = _duplicate_pk_sql_sf(_sf_db, sf_schema, sf_table, pk_cols)
            result.missing_rows_sql = _missing_rows_sql(
                pg_schema, pg_table,
                _sf_db, sf_schema, sf_table,
                pk_cols
            )

        # ── Save SQL files ───────────────────────────────────────────────────
        if save_sql:
            _save_sql_file(result, pg_table)

        return result

    # ------------------------------------------------------------------
    # AI / static mapping
    # ------------------------------------------------------------------

    def _get_mappings(
        self,
        src_cols: List[Dict], tgt_cols: List[Dict],
        pg_schema: str, pg_table: str,
        sf_schema: str, sf_table: str, sf_db: str,
        pk_hints: List[str],
    ):
        """
        Returns (mappings, explanation, generated_by).
        Tries AI first, falls back to static rule matching.
        """
        # Pair source and target columns by name
        tgt_map = {c["column_name"].upper(): c for c in tgt_cols}
        pairs = []
        for sc in src_cols:
            tc = tgt_map.get(sc["column_name"].upper())
            if tc:
                pairs.append({"source": sc, "target": tc})
            else:
                print(f"  [WARN] No target column for '{sc['column_name']}' — will skip")

        if self._ai_active:
            return self._ai_mappings(pairs, pg_schema, pg_table, sf_schema, sf_table, sf_db, pk_hints)
        else:
            print("  [INFO] No DIAL_API_KEY — using static rule matching.")
            return self._static_mappings(pairs, pk_hints)

    def _ai_mappings(
        self,
        pairs: List[Dict],
        pg_schema: str, pg_table: str,
        sf_schema: str, sf_table: str, sf_db: str,
        pk_hints: List[str],
    ):
        """Call DIAL/GPT-4o to get rule assignments for each column pair."""
        try:
            from openai import AzureOpenAI
        except ImportError:
            print("  [WARN] openai package missing — using static fallback.")
            return self._static_mappings(pairs, pk_hints)

        client = AzureOpenAI(
            api_key=self.api_key,
            api_version=self.api_version,
            azure_endpoint=self.api_base,
        )

        system_prompt = _build_system_prompt()
        user_prompt   = _build_user_prompt(
            pairs, pg_schema, pg_table, sf_schema, sf_table, sf_db, pk_hints
        )

        try:
            response = client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user",   "content": user_prompt},
                ],
                temperature=0,
                response_format={"type": "json_object"},
                extra_headers={"Api-Key": self.api_key},
            )
            raw = response.choices[0].message.content
            return _parse_ai_response(raw, pairs)
        except Exception as exc:
            print(f"  [WARN] AI call failed ({exc}) — using static fallback.")
            return self._static_mappings(pairs, pk_hints)

    @staticmethod
    def _static_mappings(pairs: List[Dict], pk_hints: List[str]):
        """Rule matching without AI — uses trigger_type_pairs from rule catalog."""
        import re, json as _json
        with open(Path(__file__).parent / "rules_catalog.json", encoding="utf-8") as f:
            catalog = _json.load(f)
        chain_order = catalog.get("chaining_order", [])
        rules_data  = catalog.get("rules", [])

        pk_hints_up = [h.upper() for h in pk_hints]
        mappings = []

        for pair in pairs:
            sc = pair["source"]
            tc = pair["target"]
            src_base = re.sub(r"\(.*\)", "", sc["data_type"]).strip().upper()
            tgt_base = re.sub(r"\(.*\)", "", tc["data_type"]).strip().upper()

            matched_rules = []
            for rule in rules_data:
                if not rule.get("auto_detect"):
                    continue
                for tp in rule["trigger_type_pairs"]:
                    s, t = tp["source"].upper(), tp["target"].upper()
                    if (s == "*" or src_base.startswith(s)) and (t == "*" or tgt_base.startswith(t)):
                        rt = _enum_val_to_rule_type(rule["enum_value"])
                        if rt and rt not in matched_rules:
                            matched_rules.append(rt)
                        break

            matched_rules.sort(
                key=lambda r: chain_order.index(r.value) if r.value in chain_order else 999
            )

            mappings.append(ColumnMapping(
                source_column=sc["column_name"],
                target_column=tc["column_name"],
                source_data_type=sc["data_type"],
                target_data_type=tc["data_type"],
                apply_rules=matched_rules,
                primary_key=sc["column_name"].upper() in pk_hints_up,
            ))

        return (
            mappings,
            "Rules assigned by static type-pair matching. Set DIAL_API_KEY to enable AI.",
            "static",
        )


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

def _build_system_prompt() -> str:
    """Build the system prompt with the FULL rule book injected."""
    rule_block = rule_book.build_prompt_block()
    return f"""You are a Senior Data Migration QA Engineer.
Your job: given source (PostgreSQL) and target (Snowflake) column metadata,
assign the correct transformation rules to each column pair and return a JSON object.

The output of your rule assignments will be used to generate SQL queries that
the user will run MANUALLY on both databases to validate data completeness.

{rule_block}

## Output Contract
Return ONLY a valid JSON object in this exact shape:
{{
  "column_mappings": [
    {{
      "source_column": "string",
      "target_column": "string",
      "source_data_type": "string",
      "target_data_type": "string",
      "primary_key": true | false,
      "ignore_validation": false,
      "apply_rules": ["RULE_ID_1", "RULE_ID_2"]
    }}
  ],
  "explanation": "Brief reasoning about the rules chosen and completeness strategy"
}}

## Strict Rules
- apply_rules values MUST match a rule "id" from the catalog above (exact match).
- NULL_STANDARDIZATION must always be the LAST rule for any nullable column.
- For JSONB / ARRAY / BYTEA columns: set ignore_validation=true, apply_rules=[].
- Mark primary_key=true for ID/key columns (usually ends in _id or named id).
- Include ALL applicable rules — do not skip rules to keep the list short.
"""


def _build_user_prompt(
    pairs: List[Dict],
    pg_schema: str, pg_table: str,
    sf_schema: str, sf_table: str, sf_db: str,
    pk_hints: List[str],
) -> str:
    pk_line = f"Primary key hints: {pk_hints}" if pk_hints else "No PK hints — please auto-detect."
    return f"""Generate a validation query plan for this migration:

Source : PostgreSQL  →  {pg_schema}.{pg_table}
Target : Snowflake   →  {sf_db}.{sf_schema}.{sf_table}
{pk_line}

Column pairs to map ({len(pairs)} total):
{json.dumps(pairs, indent=2)}

Return the JSON validation plan with all column mappings and rules.
"""


# ---------------------------------------------------------------------------
# AI response parser
# ---------------------------------------------------------------------------

def _parse_ai_response(raw_json: str, pairs: List[Dict]):
    """Parse AI JSON response into ColumnMapping list."""
    import json as _json
    try:
        data = _json.loads(raw_json)
    except Exception as exc:
        print(f"  [WARN] Could not parse AI response: {exc}")
        return QueryBuilder._static_mappings(pairs, [])

    mappings = []
    active_count = 0
    skipped_count = 0

    for cm in data.get("column_mappings", []):
        rules = []
        ignore = cm.get("ignore_validation", False)

        if not ignore:
            for rule_str in cm.get("apply_rules", []):
                rt = _enum_val_to_rule_type(rule_str)
                if rt:
                    rules.append(rt)
                else:
                    print(f"  [WARN] Unknown rule '{rule_str}' for column "
                          f"'{cm.get('source_column', '?')}' — ignored.")

        mapping = ColumnMapping(
            source_column=cm["source_column"],
            target_column=cm["target_column"],
            source_data_type=cm.get("source_data_type", ""),
            target_data_type=cm.get("target_data_type", ""),
            apply_rules=rules,
            primary_key=cm.get("primary_key", False),
            ignore_validation=ignore,
        )
        mappings.append(mapping)

        if ignore:
            skipped_count += 1
        else:
            active_count += 1

    print(f"  [AI] Parsed {len(mappings)} column mappings: "
          f"{active_count} active, {skipped_count} skipped (complex types)")

    explanation = data.get("explanation", "")
    return mappings, explanation, "ai"


# ---------------------------------------------------------------------------
# SQL builders
# ---------------------------------------------------------------------------

def _build_source_sql(
    schema: str, table: str,
    mappings: List[ColumnMapping],
    pk_cols: List[str],
) -> str:
    """Build the normalised SELECT query for PostgreSQL."""
    select_parts = []
    for cm in mappings:
        if cm.apply_rules:
            expr = rules_engine.apply_rules(
                cm.source_column, cm.apply_rules,
                DatabaseType.POSTGRESQL,
                alias=f"{cm.source_column}_normalized",
            )
        else:
            expr = f"{cm.source_column} AS {cm.source_column}_normalized"
        select_parts.append(f"    {expr}")

    order_by = ", ".join(pk_cols) if pk_cols else "1"
    cols_sql = ",\n".join(select_parts)

    return (
        f"-- ── SOURCE: PostgreSQL ── {schema}.{table} ──────────────────────\n"
        f"SELECT\n{cols_sql}\nFROM {schema}.{table}\nORDER BY {order_by};"
    )


def _build_target_sql(
    database: str, schema: str, table: str,
    mappings: List[ColumnMapping],
    pk_cols: List[str],
) -> str:
    """Build the normalised SELECT query for Snowflake."""
    select_parts = []
    for cm in mappings:
        if cm.apply_rules:
            expr = rules_engine.apply_rules(
                cm.target_column, cm.apply_rules,
                DatabaseType.SNOWFLAKE,
                alias=f"{cm.source_column}_normalized",  # same alias as source for comparison
            )
        else:
            expr = f"{cm.target_column} AS {cm.source_column}_normalized"
        select_parts.append(f"    {expr}")

    order_by = ", ".join(pk_cols) if pk_cols else "1"
    cols_sql = ",\n".join(select_parts)
    full_table = f"{database}.{schema}.{table}" if database else f"{schema}.{table}"

    return (
        f"-- ── TARGET: Snowflake ── {full_table} ──────────────────────────\n"
        f"SELECT\n{cols_sql}\nFROM {full_table}\nORDER BY {order_by};"
    )


def _row_count_sql_pg(schema: str, table: str) -> str:
    return (
        f"-- ── ROW COUNT: PostgreSQL ───────────────────────────────────────\n"
        f"SELECT COUNT(*) AS source_row_count FROM {schema}.{table};"
    )


def _row_count_sql_sf(database: str, schema: str, table: str) -> str:
    full = f"{database}.{schema}.{table}" if database else f"{schema}.{table}"
    return (
        f"-- ── ROW COUNT: Snowflake ────────────────────────────────────────\n"
        f"SELECT COUNT(*) AS target_row_count FROM {full};"
    )


def _null_check_sql_pg(schema: str, table: str, mappings: List[ColumnMapping]) -> str:
    """Generate NULL % per column query for PostgreSQL."""
    if not mappings:
        return ""
    total = len(mappings)
    null_counts = ",\n    ".join(
        f"ROUND(100.0 * SUM(CASE WHEN {cm.source_column} IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2)"
        f" AS {cm.source_column}_null_pct"
        for cm in mappings
    )
    return (
        f"-- ── NULL % CHECK: PostgreSQL ────────────────────────────────────\n"
        f"SELECT\n    COUNT(*) AS total_rows,\n    {null_counts}\n"
        f"FROM {schema}.{table};"
    )


def _null_check_sql_sf(database: str, schema: str, table: str, mappings: List[ColumnMapping]) -> str:
    """Generate NULL % per column query for Snowflake."""
    if not mappings:
        return ""
    full = f"{database}.{schema}.{table}" if database else f"{schema}.{table}"
    null_counts = ",\n    ".join(
        f"ROUND(100.0 * SUM(CASE WHEN {cm.target_column} IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2)"
        f" AS {cm.source_column}_null_pct"
        for cm in mappings
    )
    return (
        f"-- ── NULL % CHECK: Snowflake ─────────────────────────────────────\n"
        f"SELECT\n    COUNT(*) AS total_rows,\n    {null_counts}\n"
        f"FROM {full};"
    )


def _duplicate_pk_sql_sf(database: str, schema: str, table: str, pk_cols: List[str]) -> str:
    """Detect duplicate PKs in Snowflake target."""
    full = f"{database}.{schema}.{table}" if database else f"{schema}.{table}"
    pk_expr = ", ".join(pk_cols)
    return (
        f"-- ── DUPLICATE PK CHECK: Snowflake ──────────────────────────────\n"
        f"-- Expected result: 0 rows (no duplicates)\n"
        f"SELECT {pk_expr}, COUNT(*) AS cnt\n"
        f"FROM {full}\n"
        f"GROUP BY {pk_expr}\n"
        f"HAVING COUNT(*) > 1\n"
        f"ORDER BY cnt DESC;"
    )


def _missing_rows_sql(
    pg_schema: str, pg_table: str,
    sf_db: str, sf_schema: str, sf_table: str,
    pk_cols: List[str],
) -> str:
    """
    Generate a query to find PK values in source that are missing in target.
    NOTE: This query uses a sub-select approach — run the inner queries
    separately and compare, OR use a DB-link / external query tool.
    """
    sf_full = f"{sf_db}.{sf_schema}.{sf_table}" if sf_db else f"{sf_schema}.{sf_table}"
    pk_src = ", ".join(pk_cols)
    pk_tgt = ", ".join(c.upper() for c in pk_cols)
    pk_concat_src = " || '|' || ".join(f"CAST({c} AS TEXT)" for c in pk_cols)
    pk_concat_tgt = " || '|' || ".join(f"CAST({c.upper()} AS VARCHAR)" for c in pk_cols)

    return (
        f"-- ── MISSING ROWS CHECK ─────────────────────────────────────────\n"
        f"-- Step 1: Run on PostgreSQL — get all source PKs\n"
        f"SELECT {pk_src}, {pk_concat_src} AS pk_key\n"
        f"FROM {pg_schema}.{pg_table}\n"
        f"ORDER BY {pk_src};\n\n"
        f"-- Step 2: Run on Snowflake — get all target PKs\n"
        f"SELECT {pk_tgt}, {pk_concat_tgt} AS pk_key\n"
        f"FROM {sf_full}\n"
        f"ORDER BY {pk_tgt};\n\n"
        f"-- Step 3: Compare the pk_key columns — any value in Step 1 missing\n"
        f"-- from Step 2 is a ROW MISSING IN TARGET (data loss during migration)."
    )


# ---------------------------------------------------------------------------
# SQL file saver
# ---------------------------------------------------------------------------

def _save_sql_file(result: QueryResult, table_name: str):
    """Save all queries to validation_sql/<table>_validation.sql"""
    sql_dir = Path(__file__).parent.parent / "validation_sql"
    sql_dir.mkdir(exist_ok=True)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = sql_dir / f"{table_name.lower()}_validation.sql"

    sep = "=" * 70

    content = f"""-- {sep}
-- MIGRATION VALIDATOR — Generated Queries
-- Table    : {result.table_name}
-- Source   : {result.source_db}
-- Target   : {result.target_db}
-- Generated: {result.timestamp}
-- By       : {result.generated_by.upper()}
-- {sep}
-- HOW TO USE:
--   1. Run query ① on PostgreSQL  — check row counts
--   2. Run query ② on Snowflake   — check row counts
--   3. Run query ③ on PostgreSQL  — get normalised source data
--   4. Run query ④ on Snowflake   — get normalised target data
--   5. Compare ③ vs ④ result sets — they should be identical
--   6. Run ⑤ + ⑥ to compare NULL % per column
--   7. Run ⑦ on Snowflake to detect duplicate PKs
--   8. Run ⑧ steps to find missing rows
-- {sep}

-- ① ROW COUNT — PostgreSQL
{result.row_count_source_sql}

-- ② ROW COUNT — Snowflake
{result.row_count_target_sql}

-- ③ MAIN VALIDATION — PostgreSQL (normalised)
{result.source_sql}

-- ④ MAIN VALIDATION — Snowflake (normalised)
{result.target_sql}

-- ⑤ NULL % — PostgreSQL
{result.null_check_source_sql}

-- ⑥ NULL % — Snowflake
{result.null_check_target_sql}

-- ⑦ DUPLICATE PK — Snowflake
{result.duplicate_pk_sql}

-- ⑧ MISSING ROWS
{result.missing_rows_sql}
"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"\n  💾 SQL saved to: {file_path.resolve()}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _auto_detect_pks(columns: List[ColumnInfo]) -> List[str]:
    for col in columns:
        name = col.column_name.lower()
        if name in ("id",) or name.endswith("_id"):
            if any(t in col.data_type.upper() for t in ("INT", "SERIAL", "NUMBER", "BIGINT")):
                return [col.column_name]
    return []


def _enum_val_to_rule_type(enum_value: str) -> Optional[TransformationRuleType]:
    """
    Convert a rule string from AI response to TransformationRuleType.
    AI may return UPPER_CASE, lower_case, or mixed — handle all cases.

    TransformationRuleType enum values are stored in lower_case
    (e.g. 'null_standardization'), but the AI often returns UPPER_CASE
    (e.g. 'NULL_STANDARDIZATION'). Both must resolve correctly.
    """
    if not enum_value:
        return None
    # Try exact lower-case match first (canonical form)
    try:
        return TransformationRuleType(enum_value.lower())
    except ValueError:
        pass
    # Try upper-case value match (AI sometimes returns the enum NAME not value)
    # e.g. AI says 'NULL_STANDARDIZATION' which is also the enum member name
    try:
        return TransformationRuleType[enum_value.upper()]
    except KeyError:
        pass
    # Last resort: scan all members for a case-insensitive match
    search = enum_value.lower().strip()
    for member in TransformationRuleType:
        if member.value.lower() == search or member.name.lower() == search:
            return member
    return None
