"""
SQL Query Generators for Different Database Types
Generates SQL queries for data validation
"""

from typing import List, Optional, Dict
from models import DatabaseType, ColumnMapping, TransformationRuleType
from transformation_rules import rules_engine


class BaseSQLGenerator:
    """Base class for SQL generators"""
    
    def __init__(self, db_type: DatabaseType):
        self.db_type = db_type
    
    def generate_row_count_query(self, schema: str, table: str) -> str:
        """Generate query to get row count"""
        raise NotImplementedError
    
    def generate_data_query(
        self,
        schema: str,
        table: str,
        column_mappings: List[ColumnMapping]
    ) -> str:
        """Generate query to fetch and transform data"""
        raise NotImplementedError
    
    def generate_comparison_query(
        self,
        source_schema: str,
        source_table: str,
        target_schema: str,
        target_table: str,
        column_mappings: List[ColumnMapping]
    ) -> tuple:
        """Generate both source and target queries for comparison"""
        raise NotImplementedError


class MSSQLGenerator(BaseSQLGenerator):
    """SQL Server query generator"""
    
    def __init__(self):
        super().__init__(DatabaseType.MSSQL)
    
    def generate_row_count_query(self, schema: str, table: str) -> str:
        """Generate MS SQL row count query"""
        return f"""
        SELECT 
            COUNT(*) as row_count,
            '{table}' as table_name,
            GETDATE() as query_time
        FROM [{schema}].[{table}]
        """
    
    def generate_data_query(
        self,
        schema: str,
        table: str,
        column_mappings: List[ColumnMapping]
    ) -> str:
        """Generate MS SQL data query with transformations"""
        
        # Build SELECT clause with transformations
        select_clauses = []
        pk_columns = []
        
        for mapping in column_mappings:
            col = mapping.source_column
            
            if mapping.apply_rules:
                # Apply transformation rules
                expr = rules_engine.apply_rules(col, mapping.apply_rules, self.db_type)
                select_clauses.append(expr)
            else:
                select_clauses.append(f"{col} AS {col}_normalized")
            
            if mapping.primary_key:
                pk_columns.append(col)
        
        select_sql = ",\n            ".join(select_clauses)
        
        # Add row number for detailed comparison
        if pk_columns:
            pk_order = ", ".join(pk_columns)
        else:
            pk_order = "1"
        
        return f"""
        SELECT 
            {select_sql},
            ROW_NUMBER() OVER (ORDER BY {pk_order}) as rn,
            GETDATE() as extracted_at
        FROM [{schema}].[{table}]
        ORDER BY {pk_order}
        """
    
    def generate_comparison_query(
        self,
        source_schema: str,
        source_table: str,
        target_schema: str,
        target_table: str,
        column_mappings: List[ColumnMapping]
    ) -> tuple:
        """Generate source and target comparison queries"""
        
        source_query = self.generate_data_query(source_schema, source_table, column_mappings)
        
        return (source_query, None)  # Target will be generated by SnowflakeGenerator


class PostgreSQLGenerator(BaseSQLGenerator):
    """PostgreSQL query generator"""
    
    def __init__(self):
        super().__init__(DatabaseType.POSTGRESQL)
    
    def generate_row_count_query(self, schema: str, table: str) -> str:
        """Generate PostgreSQL row count query"""
        return f"""
        SELECT 
            COUNT(*) as row_count,
            '{table}' as table_name,
            CURRENT_TIMESTAMP as query_time
        FROM {schema}.{table}
        """
    
    def generate_data_query(
        self,
        schema: str,
        table: str,
        column_mappings: List[ColumnMapping]
    ) -> str:
        """Generate PostgreSQL data query with transformations"""
        
        select_clauses = []
        pk_columns = []
        
        for mapping in column_mappings:
            col = mapping.source_column
            
            if mapping.apply_rules:
                expr = rules_engine.apply_rules(col, mapping.apply_rules, self.db_type)
                select_clauses.append(expr)
            else:
                select_clauses.append(f"{col} AS {col}_normalized")
            
            if mapping.primary_key:
                pk_columns.append(col)
        
        select_sql = ",\n            ".join(select_clauses)
        
        if pk_columns:
            pk_order = ", ".join(pk_columns)
        else:
            pk_order = "1"
        
        return f"""
        SELECT 
            {select_sql},
            ROW_NUMBER() OVER (ORDER BY {pk_order}) as rn,
            CURRENT_TIMESTAMP as extracted_at
        FROM {schema}.{table}
        ORDER BY {pk_order}
        """
    
    def generate_comparison_query(
        self,
        source_schema: str,
        source_table: str,
        target_schema: str,
        target_table: str,
        column_mappings: List[ColumnMapping]
    ) -> tuple:
        """Generate source and target comparison queries"""
        
        source_query = self.generate_data_query(source_schema, source_table, column_mappings)
        
        return (source_query, None)  # Target will be generated by SnowflakeGenerator


class SnowflakeGenerator(BaseSQLGenerator):
    """Snowflake query generator"""
    
    def __init__(self):
        super().__init__(DatabaseType.SNOWFLAKE)
    
    def generate_row_count_query(self, database: str, schema: str, table: str) -> str:
        """Generate Snowflake row count query"""
        return f"""
        SELECT 
            COUNT(*) as row_count,
            '{table}' as table_name,
            CURRENT_TIMESTAMP() as query_time
        FROM {database}.{schema}.{table}
        """
    
    def generate_data_query(
        self,
        database: str,
        schema: str,
        table: str,
        column_mappings: List[ColumnMapping]
    ) -> str:
        """Generate Snowflake data query with transformations"""
        
        select_clauses = []
        pk_columns = []
        
        for mapping in column_mappings:
            col = mapping.target_column
            
            if mapping.apply_rules:
                expr = rules_engine.apply_rules(col, mapping.apply_rules, self.db_type)
                select_clauses.append(expr)
            else:
                select_clauses.append(f"{col} AS {col}_normalized")
            
            if mapping.primary_key:
                pk_columns.append(col)
        
        select_sql = ",\n            ".join(select_clauses)
        
        if pk_columns:
            pk_order = ", ".join(pk_columns)
        else:
            pk_order = "1"
        
        return f"""
        SELECT 
            {select_sql},
            ROW_NUMBER() OVER (ORDER BY {pk_order}) as rn,
            CURRENT_TIMESTAMP() as extracted_at
        FROM {database}.{schema}.{table}
        ORDER BY {pk_order}
        """
    
    def generate_comparison_query(
        self,
        source_database: str,
        source_schema: str,
        source_table: str,
        target_database: str,
        target_schema: str,
        target_table: str,
        column_mappings: List[ColumnMapping]
    ) -> tuple:
        """Generate source and target comparison queries"""
        
        source_query = self.generate_data_query(
            source_database, source_schema, source_table, column_mappings
        )
        
        target_query = self.generate_data_query(
            target_database, target_schema, target_table, column_mappings
        )
        
        return (source_query, target_query)


class QueryGenerator:
    """Factory for generating SQL queries"""
    
    def __init__(self):
        self.generators: Dict[DatabaseType, BaseSQLGenerator] = {
            DatabaseType.MSSQL: MSSQLGenerator(),
            DatabaseType.POSTGRESQL: PostgreSQLGenerator(),
            DatabaseType.SNOWFLAKE: SnowflakeGenerator(),
        }
    
    def get_generator(self, db_type: DatabaseType) -> BaseSQLGenerator:
        """Get generator for database type"""
        return self.generators.get(db_type)
    
    def generate_validation_queries(
        self,
        source_type: DatabaseType,
        source_schema: str,
        source_table: str,
        source_database: Optional[str] = None,
        target_type: DatabaseType = DatabaseType.SNOWFLAKE,
        target_database: Optional[str] = None,
        target_schema: Optional[str] = None,
        target_table: Optional[str] = None,
        column_mappings: Optional[List[ColumnMapping]] = None
    ) -> Dict[str, str]:
        """
        Generate complete validation queries
        
        Returns:
            Dictionary with 'source_row_count', 'target_row_count', 'source_data', 'target_data' queries
        """
        
        if not column_mappings:
            column_mappings = []
        
        source_gen = self.get_generator(source_type)
        target_gen = self.get_generator(target_type)
        
        queries = {}
        
        # Row count queries
        if source_type == DatabaseType.MSSQL:
            queries['source_row_count'] = source_gen.generate_row_count_query(source_schema, source_table)
        elif source_type == DatabaseType.POSTGRESQL:
            queries['source_row_count'] = source_gen.generate_row_count_query(source_schema, source_table)
        
        if target_type == DatabaseType.SNOWFLAKE:
            queries['target_row_count'] = target_gen.generate_row_count_query(
                target_database, target_schema, target_table
            )
        
        # Data queries
        if source_type == DatabaseType.MSSQL:
            queries['source_data'] = source_gen.generate_data_query(
                source_schema, source_table, column_mappings
            )
        elif source_type == DatabaseType.POSTGRESQL:
            queries['source_data'] = source_gen.generate_data_query(
                source_schema, source_table, column_mappings
            )
        
        if target_type == DatabaseType.SNOWFLAKE:
            queries['target_data'] = target_gen.generate_data_query(
                target_database, target_schema, target_table, column_mappings
            )
        
        return queries


# Create singleton instance
query_generator = QueryGenerator()
